<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CMS Login - Church of Uganda Youth Platform</title>
    @php try { $adminLogo = \App\Models\SiteSetting::get('logo'); $adminFavicon = \App\Models\SiteSetting::get('favicon'); } catch (\Throwable $e) { $adminLogo=null; $adminFavicon=null; } @endphp
    @if(!empty($adminFavicon))<link rel="icon" href="{{ asset('storage/'.$adminFavicon) }}">@endif
    <style>*{box-sizing:border-box}body{margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;background:#f3f4f6;font-family:Arial,sans-serif}.login-card{width:100%;max-width:420px;background:#fff;padding:32px;border-radius:16px;box-shadow:0 15px 40px rgba(0,0,0,.08)}.brand-logo{max-height:56px;max-width:220px;object-fit:contain;display:block;margin:0 auto 14px}h1{margin:0 0 8px;font-size:24px}.subtitle{color:#6b7280;margin-bottom:24px}.form-group{margin-bottom:18px}label{display:block;margin-bottom:6px;font-weight:600}input[type=email],input[type=password]{width:100%;padding:12px 14px;border:1px solid #d1d5db;border-radius:8px;font-size:15px}.remember{display:flex;gap:8px;align-items:center;margin-bottom:20px}button{width:100%;border:0;background:#4b2e83;color:#fff;padding:13px;border-radius:8px;font-size:16px;cursor:pointer}.error{background:#fee2e2;color:#991b1b;border-radius:8px;padding:10px 12px;margin-bottom:16px}.public-link{text-align:center;margin-top:18px;color:#6b7280}.public-link a{color:#4b2e83;font-weight:700;text-decoration:none}</style>
</head>
<body><div class="login-card">@if(!empty($adminLogo))<img class="brand-logo" src="{{ asset('storage/'.$adminLogo) }}" alt="Site logo">@endif<h1>CMS Login</h1><div class="subtitle">For authorised Church of Uganda Youth Platform administrators.</div>@if ($errors->any())<div class="error" data-auth-flash role="alert">{{ $errors->first() }}</div>@endif<form method="POST" action="{{ route('admin.login.attempt') }}">@csrf<div class="form-group"><label for="email">Email Address</label><input id="email" type="email" name="email" value="{{ old('email') }}" required autofocus autocomplete="email"></div><div class="form-group"><label for="password">Password</label><span class="pw-wrap" style="display:block;position:relative"><input id="password" type="password" name="password" required autocomplete="current-password"><button type="button" class="pw-toggle" data-pw-toggle="password" aria-label="Show password" aria-pressed="false" style="position:absolute;right:8px;top:50%;transform:translateY(-50%);border:1px solid #d1d5db;background:#fff;border-radius:8px;padding:6px 9px;cursor:pointer">👁</button></span></div><label class="remember"><input type="checkbox" name="remember" value="1"> Remember me</label><button type="submit">Sign In to CMS</button></form><div class="public-link">Youth member? <a href="{{ route('login') }}">Use Youth Login</a></div></div><style>[data-auth-flash]{transition:opacity .5s ease}[data-auth-flash].is-fading{opacity:0}</style><script>(function(){document.querySelectorAll('[data-pw-toggle]').forEach(function(b){var i=document.getElementById(b.getAttribute('data-pw-toggle'));if(!i)return;b.addEventListener('click',function(){var s=i.type==='password';i.type=s?'text':'password';b.setAttribute('aria-pressed',String(s));b.setAttribute('aria-label',s?'Hide password':'Show password');b.textContent=s?'🙈':'👁'})});document.querySelectorAll('[data-auth-flash]').forEach(function(el){setTimeout(function(){el.classList.add('is-fading');setTimeout(function(){el.remove()},550)},5000)})})();</script></body></html>