@extends('admin.layout')
@section('title',$course->title.' Quizzes')
@section('content')
<div class="page-head"><div><h1><i class="fas fa-circle-question"></i> {{ $course->title }} – Quizzes</h1><p>Manage assessments and questions for this course.</p></div><button class="btn btn-primary" data-open-modal="quiz-create"><i class="fas fa-plus"></i> Add Quiz</button></div>
<div data-tabs>
<div class="tabs"><button class="tab active" data-tab-target="quizzes-list"><i class="fas fa-list"></i> Quizzes <span class="tab-count">{{ $quizzes->count() }}</span></button><button class="tab" data-tab-target="quiz-summary"><i class="fas fa-chart-column"></i> Summary</button></div>
<section id="quizzes-list" class="tab-panel active"><div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Quiz</th><th>Pass mark</th><th>Attempts</th><th>Questions</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($quizzes as $quiz)<tr><td><strong>{{ $quiz->title }}</strong></td><td>{{ $quiz->pass_mark }}%</td><td>{{ $quiz->max_attempts ?: 'Unlimited' }}</td><td>{{ $quiz->questions->count() }}</td><td><span class="badge {{ $quiz->is_published?'badge-success':'badge-warning' }}">{{ $quiz->is_published?'Published':'Draft' }}</span></td><td><div class="actions"><button class="icon-btn" data-open-modal="quiz-view-{{ $quiz->id }}"><i class="fas fa-eye"></i></button><button class="icon-btn" data-open-modal="quiz-edit-{{ $quiz->id }}"><i class="fas fa-pen"></i></button><button class="icon-btn" data-open-modal="question-create-{{ $quiz->id }}" title="Add question"><i class="fas fa-plus"></i></button><button class="icon-btn" data-open-modal="quiz-delete-{{ $quiz->id }}"><i class="fas fa-trash"></i></button></div></td></tr>@empty<tr><td colspan="6" class="empty">No quizzes yet.</td></tr>@endforelse</tbody></table></div></div></section>
<section id="quiz-summary" class="tab-panel"><div class="grid stats-grid">@php $questionCount=$quizzes->sum(fn($q)=>$q->questions->count()); $published=$quizzes->where('is_published',true)->count(); @endphp<div class="card stat-card" style="border-left:5px solid #7c3aed"><div class="stat-icon"><i class="fas fa-circle-question"></i></div><div><strong>{{ $quizzes->count() }}</strong><span>Total quizzes</span></div></div><div class="card stat-card" style="border-left:5px solid #16a34a"><div class="stat-icon"><i class="fas fa-circle-check"></i></div><div><strong>{{ $published }}</strong><span>Published</span></div></div><div class="card stat-card" style="border-left:5px solid #2563eb"><div class="stat-icon"><i class="fas fa-list"></i></div><div><strong>{{ $questionCount }}</strong><span>Questions</span></div></div></div></section>
</div>

<div id="quiz-create" class="modal"><div class="modal-card"><div class="modal-head"><h2>Add Quiz</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="POST" action="{{ route('admin.courses.quizzes.store',$course) }}">@csrf<div class="form-grid"><label>Quiz title<input name="title" required></label><label>Pass mark (%)<input name="pass_mark" type="number" min="1" max="100" value="70" required></label><label>Max attempts<input name="max_attempts" type="number" min="1" max="20"></label><label class="checkbox"><input type="checkbox" name="is_published" value="1"> Published</label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-floppy-disk"></i> Save Quiz</button></div></form></div></div>

@foreach($quizzes as $quiz)
<div id="quiz-view-{{ $quiz->id }}" class="modal"><div class="modal-card large"><div class="modal-head"><h2>{{ $quiz->title }}</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><div class="detail-grid"><div class="detail-item"><span>Pass mark</span><strong>{{ $quiz->pass_mark }}%</strong></div><div class="detail-item"><span>Max attempts</span><strong>{{ $quiz->max_attempts ?: 'Unlimited' }}</strong></div><div class="detail-item"><span>Status</span><strong>{{ $quiz->is_published?'Published':'Draft' }}</strong></div><div class="detail-item"><span>Questions</span><strong>{{ $quiz->questions->count() }}</strong></div></div><h3>Questions</h3><div class="table-wrap"><table><thead><tr><th>#</th><th>Question</th><th>Type</th><th>Points</th><th>Actions</th></tr></thead><tbody>@forelse($quiz->questions as $question)<tr><td>{{ $question->position }}</td><td>{{ $question->question }}</td><td>{{ ucwords(str_replace('_',' ',$question->type)) }}</td><td>{{ $question->points }}</td><td><div class="actions"><button class="icon-btn" data-close-modal data-open-modal="question-edit-{{ $question->id }}"><i class="fas fa-pen"></i></button><button class="icon-btn" data-close-modal data-open-modal="question-delete-{{ $question->id }}"><i class="fas fa-trash"></i></button></div></td></tr>@empty<tr><td colspan="5" class="empty">No questions yet.</td></tr>@endforelse</tbody></table></div><div class="modal-actions"><button class="btn btn-light" data-close-modal>Close</button><button class="btn btn-primary" data-close-modal data-open-modal="question-create-{{ $quiz->id }}"><i class="fas fa-plus"></i> Add Question</button></div></div></div>
<div id="quiz-edit-{{ $quiz->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>Edit Quiz</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="POST" action="{{ route('admin.quizzes.update',$quiz) }}">@csrf @method('PUT')<div class="form-grid"><label>Quiz title<input name="title" value="{{ $quiz->title }}" required></label><label>Pass mark (%)<input name="pass_mark" type="number" min="1" max="100" value="{{ $quiz->pass_mark }}" required></label><label>Max attempts<input name="max_attempts" type="number" min="1" max="20" value="{{ $quiz->max_attempts }}"></label><label class="checkbox"><input type="checkbox" name="is_published" value="1" @checked($quiz->is_published)> Published</label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-floppy-disk"></i> Update Quiz</button></div></form></div></div>
<div id="question-create-{{ $quiz->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>Add Question · {{ $quiz->title }}</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="POST" action="{{ route('admin.quizzes.questions.store',$quiz) }}">@csrf<div class="form-grid"><label class="span-2">Question<input name="question" required></label><label>Type<select name="type"><option value="single_choice">Single choice</option><option value="true_false">True/False</option><option value="text">Text</option></select></label><label>Correct answer<input name="correct_answer" required></label><label>Points<input name="points" type="number" value="1" min="1" max="100"></label><label>Position<input name="position" type="number" min="1"></label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-plus"></i> Add Question</button></div></form></div></div>
<div id="quiz-delete-{{ $quiz->id }}" class="modal"><div class="modal-card small"><div class="modal-head"><h2>Delete Quiz?</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><p class="danger-copy">Delete <strong>{{ $quiz->title }}</strong> and all its questions?</p><form method="POST" action="{{ route('admin.quizzes.destroy',$quiz) }}">@csrf @method('DELETE')<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-danger"><i class="fas fa-trash"></i> Delete</button></div></form></div></div>
@foreach($quiz->questions as $question)
<div id="question-edit-{{ $question->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>Edit Question</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="POST" action="{{ route('admin.quizzes.questions.update',[$quiz,$question]) }}">@csrf @method('PUT')<div class="form-grid"><label class="span-2">Question<input name="question" value="{{ $question->question }}" required></label><label>Type<select name="type">@foreach(['single_choice','true_false','text'] as $type)<option value="{{ $type }}" @selected($question->type===$type)>{{ ucwords(str_replace('_',' ',$type)) }}</option>@endforeach</select></label><label>Correct answer<input name="correct_answer" value="{{ is_array($question->correct_answer) ? ($question->correct_answer[0]??'') : $question->correct_answer }}" required></label><label>Points<input name="points" type="number" min="1" max="100" value="{{ $question->points }}"></label><label>Position<input name="position" type="number" min="1" value="{{ $question->position }}"></label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-floppy-disk"></i> Update Question</button></div></form></div></div>
<div id="question-delete-{{ $question->id }}" class="modal"><div class="modal-card small"><div class="modal-head"><h2>Delete Question?</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><p class="danger-copy">Delete this question from <strong>{{ $quiz->title }}</strong>?</p><form method="POST" action="{{ route('admin.quizzes.questions.destroy',[$quiz,$question]) }}">@csrf @method('DELETE')<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-danger">Delete</button></div></form></div></div>
@endforeach
@endforeach
@endsection
