@extends('admin.layout')
@section('title','Notifications')
@section('content')
@php $max=max(1,(int)collect($chart)->max()); @endphp
<div class="page-head"><div><h1><i class="fas fa-bell"></i> Notifications</h1><p>Create and monitor youth platform notifications.</p></div><button class="btn btn-primary" data-open-modal="notification-create"><i class="fas fa-plus"></i> Add Notification</button></div>
<div data-tabs>
    <div class="tabs"><button class="tab active" data-tab-target="notifications-overview"><i class="fas fa-chart-column"></i> Overview</button><button class="tab" data-tab-target="notifications-list"><i class="fas fa-list"></i> Notifications <span class="tab-count">{{ $items->total() }}</span></button></div>
    <section id="notifications-overview" class="tab-panel active">
        <div class="grid stats-grid"><div class="card stat-card stat-purple"><div class="stat-icon"><i class="fas fa-bell"></i></div><div><strong>{{ number_format($stats['total']) }}</strong><span>Total notifications</span></div></div><div class="card stat-card stat-green"><div class="stat-icon"><i class="fas fa-circle-check"></i></div><div><strong>{{ number_format($stats['active']) }}</strong><span>Active</span></div></div><div class="card stat-card stat-orange"><div class="stat-icon"><i class="fas fa-clock"></i></div><div><strong>{{ number_format($stats['scheduled']) }}</strong><span>Scheduled</span></div></div><div class="card stat-card stat-blue"><div class="stat-icon"><i class="fas fa-layer-group"></i></div><div><strong>{{ number_format($stats['all_channel']) }}</strong><span>All-channel messages</span></div></div></div>
        <div class="card"><h3 style="margin-top:0">Notifications by channel</h3><div class="mini-bars">@forelse($chart as $label=>$value)<div class="mini-row"><span>{{ ucwords(str_replace('_',' ',$label)) }}</span><div class="mini-track"><i style="width:{{ ($value/$max)*100 }}%"></i></div><strong>{{ $value }}</strong></div>@empty<div class="empty">No notification data yet.</div>@endforelse</div></div>
    </section>
    <section id="notifications-list" class="tab-panel">
        <div class="card"><form class="filters" method="get"><input name="q" value="{{ $filters['q'] }}" placeholder="Search title or message"><select name="channel"><option value="">All channels</option>@foreach(['in_app','push','email','all'] as $c)<option value="{{ $c }}" @selected($filters['channel']===$c)>{{ ucwords(str_replace('_',' ',$c)) }}</option>@endforeach</select><select name="age_category"><option value="">All ages</option>@foreach(['teen','youth','young_adult','all'] as $a)<option value="{{ $a }}" @selected($filters['age_category']===$a)>{{ ucwords(str_replace('_',' ',$a)) }}</option>@endforeach</select><button class="btn btn-primary"><i class="fas fa-search"></i> Filter</button><a class="btn btn-light" href="{{ route('admin.notifications.index') }}#notifications-list">Reset</a></form></div>
        <div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Notification</th><th>Channel</th><th>Audience</th><th>Schedule</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($items as $n)<tr><td><strong>{{ $n->title }}</strong><small>{{ Str::limit($n->body,90) }}</small></td><td><span class="badge">{{ ucwords(str_replace('_',' ',$n->channel)) }}</span></td><td>{{ ucwords(str_replace('_',' ',$n->age_category)) }}<small>{{ $n->organisationUnit?->name ?: 'All Church' }}</small></td><td>{{ $n->scheduled_at?->format('d M Y H:i') ?: 'Immediate' }}</td><td><span class="badge {{ $n->is_active?'badge-success':'badge-warning' }}">{{ $n->is_active?'Active':'Inactive' }}</span></td><td><div class="actions"><button class="icon-btn" data-open-modal="notification-view-{{ $n->id }}" title="View"><i class="fas fa-eye"></i></button><button class="icon-btn" data-open-modal="notification-edit-{{ $n->id }}" title="Edit"><i class="fas fa-pen"></i></button><button class="icon-btn" data-open-modal="notification-delete-{{ $n->id }}" title="Delete"><i class="fas fa-trash"></i></button></div></td></tr>@empty<tr><td colspan="6" class="empty">No notifications found.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $items->withQueryString()->links() }}</div></div>
    </section>
</div>

<div id="notification-create" class="modal"><div class="modal-card"><div class="modal-head"><h2>Add Notification</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="post" action="{{ route('admin.notifications.store') }}">@csrf<div class="form-grid"><label>Title<input name="title" required></label><label>Channel<select name="channel">@foreach(['in_app','push','email','all'] as $c)<option value="{{ $c }}">{{ ucwords(str_replace('_',' ',$c)) }}</option>@endforeach</select></label><label class="span-2">Message<textarea name="body" rows="4" required></textarea></label><label>Age category<select name="age_category">@foreach(['all','teen','youth','young_adult'] as $a)<option value="{{ $a }}">{{ ucwords(str_replace('_',' ',$a)) }}</option>@endforeach</select></label><label>Target unit ID<input name="organisation_unit_id" placeholder="Optional"></label><label>Schedule<input type="datetime-local" name="scheduled_at"></label><label>Action URL<input name="action_url" placeholder="Optional"></label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-paper-plane"></i> Queue Notification</button></div></form></div></div>

@foreach($items as $n)
<div id="notification-view-{{ $n->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>{{ $n->title }}</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><div class="detail-grid"><div class="detail-item"><span>Channel</span><strong>{{ ucwords(str_replace('_',' ',$n->channel)) }}</strong></div><div class="detail-item"><span>Audience</span><strong>{{ ucwords(str_replace('_',' ',$n->age_category)) }}</strong></div><div class="detail-item"><span>Church Unit</span><strong>{{ $n->organisationUnit?->name ?: 'All Church' }}</strong></div><div class="detail-item"><span>Schedule</span><strong>{{ $n->scheduled_at?->format('d M Y H:i') ?: 'Immediate' }}</strong></div><div class="detail-item"><span>Status</span><strong>{{ $n->is_active?'Active':'Inactive' }}</strong></div><div class="detail-item"><span>Sent</span><strong>{{ $n->sent_at?->format('d M Y H:i') ?: 'Not sent yet' }}</strong></div><div class="detail-item span-2"><span>Message</span><strong>{{ $n->body }}</strong></div><div class="detail-item span-2"><span>Action URL</span><strong>{{ $n->action_url ?: '—' }}</strong></div></div><div class="modal-actions"><button class="btn btn-light" data-close-modal>Close</button><button class="btn btn-primary" data-close-modal data-open-modal="notification-edit-{{ $n->id }}"><i class="fas fa-pen"></i> Edit</button></div></div></div>
<div id="notification-edit-{{ $n->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>Edit Notification</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="post" action="{{ route('admin.notifications.update',$n) }}">@csrf @method('PUT')<div class="form-grid"><label>Title<input name="title" value="{{ $n->title }}" required></label><label>Channel<select name="channel">@foreach(['in_app','push','email','all'] as $c)<option value="{{ $c }}" @selected($n->channel===$c)>{{ ucwords(str_replace('_',' ',$c)) }}</option>@endforeach</select></label><label class="span-2">Message<textarea name="body" rows="4" required>{{ $n->body }}</textarea></label><label>Age category<select name="age_category">@foreach(['all','teen','youth','young_adult'] as $a)<option value="{{ $a }}" @selected($n->age_category===$a)>{{ ucwords(str_replace('_',' ',$a)) }}</option>@endforeach</select></label><label>Target unit ID<input name="organisation_unit_id" value="{{ $n->organisation_unit_id }}"></label><label>Schedule<input type="datetime-local" name="scheduled_at" value="{{ $n->scheduled_at?->format('Y-m-d\TH:i') }}"></label><label>Action URL<input name="action_url" value="{{ $n->action_url }}"></label><label class="checkbox"><input type="checkbox" name="is_active" value="1" @checked($n->is_active)> Active</label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-floppy-disk"></i> Update Notification</button></div></form></div></div>
<div id="notification-delete-{{ $n->id }}" class="modal"><div class="modal-card small"><div class="modal-head"><h2>Delete Notification?</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><p class="danger-copy">Delete <strong>{{ $n->title }}</strong>? This action cannot be undone.</p><form method="post" action="{{ route('admin.notifications.destroy',$n) }}">@csrf @method('DELETE')<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-danger"><i class="fas fa-trash"></i> Delete</button></div></form></div></div>
@endforeach
@endsection
@push('styles')<style>.stat-card{border-left:5px solid var(--primary)}.stat-green{border-left-color:#16a34a}.stat-orange{border-left-color:#ea580c}.stat-blue{border-left-color:#2563eb}.stat-purple{border-left-color:#7c3aed}.mini-bars{display:grid;gap:12px}.mini-row{display:grid;grid-template-columns:120px 1fr 45px;gap:10px;align-items:center}.mini-track{height:10px;background:#eef2f7;border-radius:99px;overflow:hidden}.mini-track i{display:block;height:100%;background:var(--primary);border-radius:99px}</style>@endpush
