@extends('admin.layout')
@section('title','Media Library')
@section('content')
@php $maxType=max(1,(int)collect($typeCounts)->max()); @endphp
<div class="page-head"><div><h1><i class="fas fa-photo-film"></i> Media Library</h1><p>Manage images, audio, video and document resources for the youth platform.</p></div><button class="btn btn-primary" data-open-modal="media-create"><i class="fas fa-plus"></i> Add Media</button></div>
<div data-tabs>
    <div class="tabs"><button class="tab active" data-tab-target="media-overview"><i class="fas fa-chart-column"></i> Overview</button><button class="tab" data-tab-target="media-list"><i class="fas fa-list"></i> Media <span class="tab-count">{{ $items->total() }}</span></button></div>
    <section id="media-overview" class="tab-panel active">
        <div class="grid stats-grid"><div class="card stat-card stat-purple"><div class="stat-icon"><i class="fas fa-layer-group"></i></div><div><strong>{{ number_format($stats['total']) }}</strong><span>Total media</span></div></div><div class="card stat-card stat-green"><div class="stat-icon"><i class="fas fa-circle-check"></i></div><div><strong>{{ number_format($stats['published']) }}</strong><span>Published</span></div></div><div class="card stat-card stat-blue"><div class="stat-icon"><i class="fas fa-image"></i></div><div><strong>{{ number_format($stats['images']) }}</strong><span>Images</span></div></div><div class="card stat-card stat-orange"><div class="stat-icon"><i class="fas fa-file-lines"></i></div><div><strong>{{ number_format($stats['documents']) }}</strong><span>Documents</span></div></div></div>
        <div class="card"><h3 style="margin-top:0"><i class="fas fa-chart-column"></i> Media by type</h3><div class="mini-chart">@foreach(['image'=>'Images','audio'=>'Audio','video'=>'Video','document'=>'Documents'] as $key=>$label)@php $count=(int)($typeCounts[$key]??0); @endphp<div class="chart-row"><span>{{ $label }}</span><div class="chart-track"><div class="chart-bar" style="width:{{ ($count/$maxType)*100 }}%"></div></div><strong>{{ $count }}</strong></div>@endforeach</div></div>
    </section>
    <section id="media-list" class="tab-panel">
        <div class="card"><form method="get" class="filters"><input type="search" name="q" value="{{ $filters['q'] }}" placeholder="Search title, alt text or MIME type"><select name="type"><option value="">All types</option>@foreach(['image'=>'Images','audio'=>'Audio','video'=>'Video','document'=>'Documents'] as $value=>$label)<option value="{{ $value }}" @selected($filters['type']===$value)>{{ $label }}</option>@endforeach</select><select name="status"><option value="">All statuses</option><option value="published" @selected($filters['status']==='published')>Published</option><option value="draft" @selected($filters['status']==='draft')>Draft</option></select><button class="btn btn-primary"><i class="fas fa-magnifying-glass"></i> Search</button><a class="btn btn-light" href="{{ route('admin.media.index') }}#media-list">Reset</a></form></div>
        <div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Title</th><th>Type</th><th>File</th><th>Status</th><th>Uploaded</th><th>Actions</th></tr></thead><tbody>@forelse($items as $item)<tr><td><strong>{{ $item->title }}</strong><small>{{ $item->alt_text ?: 'No alt text provided' }}</small></td><td>{{ ucfirst($item->type) }}</td><td>{{ $item->mime_type }}<small>{{ number_format(((int)$item->file_size)/1024,1) }} KB</small></td><td><span class="badge {{ $item->is_published?'badge-success':'badge-warning' }}">{{ $item->is_published?'Published':'Draft' }}</span></td><td>{{ optional($item->created_at)->format('d M Y') }}</td><td><div class="actions"><button class="icon-btn" data-open-modal="media-view-{{ $item->id }}"><i class="fas fa-eye"></i></button><button class="icon-btn" data-open-modal="media-edit-{{ $item->id }}"><i class="fas fa-pen"></i></button><button class="icon-btn" data-open-modal="media-delete-{{ $item->id }}"><i class="fas fa-trash"></i></button></div></td></tr>@empty<tr><td colspan="6" class="empty">No media items found.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $items->withQueryString()->links() }}</div></div>
    </section>
</div>

<div id="media-create" class="modal"><div class="modal-card"><div class="modal-head"><h2>Add Media</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="post" enctype="multipart/form-data" action="{{ route('admin.media.store') }}">@csrf<div class="form-grid"><label>Title<input name="title" required></label><label>Type<select name="type" required><option value="image">Image</option><option value="audio">Audio</option><option value="video">Video</option><option value="document">Document</option></select></label><label class="span-2">Accessible alt text<input name="alt_text"></label><label class="span-2">File<input type="file" name="file" required></label><label class="checkbox span-2"><input type="checkbox" name="is_published" value="1"> Published</label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-cloud-arrow-up"></i> Upload Media</button></div></form></div></div>

@foreach($items as $item)
<div id="media-view-{{ $item->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>{{ $item->title }}</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><div class="detail-grid"><div class="detail-item"><span>Type</span><strong>{{ ucfirst($item->type) }}</strong></div><div class="detail-item"><span>Status</span><strong>{{ $item->is_published?'Published':'Draft' }}</strong></div><div class="detail-item"><span>MIME type</span><strong>{{ $item->mime_type }}</strong></div><div class="detail-item"><span>File size</span><strong>{{ number_format(((int)$item->file_size)/1024,1) }} KB</strong></div><div class="detail-item span-2"><span>Alt text</span><strong>{{ $item->alt_text ?: 'Not provided' }}</strong></div><div class="detail-item span-2"><span>Stored path</span><strong>{{ $item->file_path }}</strong></div></div><div class="modal-actions"><button class="btn btn-light" data-close-modal>Close</button><button class="btn btn-primary" data-close-modal data-open-modal="media-edit-{{ $item->id }}"><i class="fas fa-pen"></i> Edit</button></div></div></div>
<div id="media-edit-{{ $item->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>Edit Media</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="post" enctype="multipart/form-data" action="{{ route('admin.media.update',$item) }}">@csrf @method('PUT')<div class="form-grid"><label>Title<input name="title" value="{{ $item->title }}" required></label><label>Type<select name="type">@foreach(['image','audio','video','document'] as $type)<option value="{{ $type }}" @selected($item->type===$type)>{{ ucfirst($type) }}</option>@endforeach</select></label><label class="span-2">Accessible alt text<input name="alt_text" value="{{ $item->alt_text }}"></label><label class="span-2">Replace file<input type="file" name="file"><small>Leave blank to keep the existing file.</small></label><label class="checkbox span-2"><input type="checkbox" name="is_published" value="1" @checked($item->is_published)> Published</label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-floppy-disk"></i> Update Media</button></div></form></div></div>
<div id="media-delete-{{ $item->id }}" class="modal"><div class="modal-card small"><div class="modal-head"><h2>Delete Media?</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><p class="danger-copy">Delete <strong>{{ $item->title }}</strong> and its stored file? This action cannot be undone.</p><form method="post" action="{{ route('admin.media.destroy',$item) }}">@csrf @method('DELETE')<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-danger"><i class="fas fa-trash"></i> Delete</button></div></form></div></div>
@endforeach
@endsection
@push('styles')<style>.stat-card{border-left:5px solid var(--primary)}.stat-purple{border-left-color:#7c3aed}.stat-green{border-left-color:#16a34a}.stat-blue{border-left-color:#2563eb}.stat-orange{border-left-color:#ea580c}.mini-chart{display:grid;gap:12px}.chart-row{display:grid;grid-template-columns:110px 1fr 42px;gap:10px;align-items:center}.chart-track{height:12px;background:#eef2f7;border-radius:99px;overflow:hidden}.chart-bar{height:100%;background:var(--primary);border-radius:99px}.chart-row strong{text-align:right}</style>@endpush
