@extends('admin.layout')
@section('title','Online Service')
@section('content')
<div class="page-head"><div><h1><i class="fas fa-tower-broadcast"></i> Online Service</h1><p>Manage livestreams, service links, speakers, dates and thumbnails.</p></div><button class="btn btn-primary" data-open-modal="service-add"><i class="fas fa-plus"></i> Add service</button></div>
<div class="card"><form class="filters" method="GET"><input name="q" placeholder="Search title, speaker or platform" value="{{ request('q') }}"><select name="status"><option value="">All statuses</option>@foreach(['scheduled','live','completed','cancelled'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ ucfirst($s) }}</option>@endforeach</select><button class="btn btn-primary">Filter</button><a class="btn btn-light" href="{{ route('admin.online-services.index') }}">Reset</a></form></div>
<div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Service</th><th>Platform</th><th>Date & time</th><th>Speaker</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($services as $s)<tr><td><strong>{{ $s->title }}</strong>@if($s->thumbnail_path)<small>Thumbnail uploaded</small>@endif</td><td>{{ $s->platform }}</td><td>{{ \Illuminate\Support\Carbon::parse($s->starts_at)->format('d M Y H:i') }}</td><td>{{ $s->speaker ?: '—' }}</td><td><span class="badge {{ $s->status==='live' ? 'badge-success' : '' }}">{{ ucfirst($s->status) }}</span></td><td class="actions"><a class="btn btn-light" target="_blank" rel="noopener" href="{{ $s->stream_url }}">Open</a><button class="btn btn-light" data-open-modal="service-edit-{{ $s->id }}">Edit</button><button class="btn btn-danger" data-open-modal="service-delete-{{ $s->id }}">Delete</button></td></tr>@empty<tr><td colspan="6" class="empty">No online services found.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $services->links() }}</div></div>
<div class="modal" id="service-add"><div class="modal-card large"><div class="modal-head"><h2>Add Online Service</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="POST" enctype="multipart/form-data" action="{{ route('admin.online-services.store') }}">@csrf @include('admin.media._online-service-fields',['service'=>null])<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary">Save</button></div></form></div></div>
@foreach($services as $s)<div class="modal" id="service-edit-{{ $s->id }}"><div class="modal-card large"><div class="modal-head"><h2>Edit Online Service</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="POST" enctype="multipart/form-data" action="{{ route('admin.online-services.update',$s->id) }}">@csrf @method('PUT') @include('admin.media._online-service-fields',['service'=>$s])<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary">Update</button></div></form></div></div><div class="modal" id="service-delete-{{ $s->id }}"><div class="modal-card small"><div class="modal-head"><h2>Delete online service?</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><p>{{ $s->title }}</p><form method="POST" action="{{ route('admin.online-services.destroy',$s->id) }}">@csrf @method('DELETE')<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-danger">Delete</button></div></form></div></div>@endforeach
@endsection
