<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>@yield('title','Church of Uganda Youth Platform')</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
<style>
:root{--primary:#4b2e83;--dark:#2f1d52;--bg:#f7f8fc;--text:#1f2937;--muted:#6b7280;--border:#e5e7eb}*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;background:var(--bg);color:var(--text)}a{text-decoration:none;color:inherit}.site-header{background:#fff;border-bottom:1px solid var(--border);position:sticky;top:0;z-index:30}.nav{max-width:1180px;margin:auto;padding:14px 20px;display:flex;align-items:center;gap:18px}.brand{font-weight:800;color:var(--primary);display:flex;align-items:center;gap:8px;margin-right:auto}.nav-links{display:flex;align-items:center;gap:14px;flex-wrap:wrap}.nav-links a{font-size:14px;font-weight:700;color:#374151}.btn{display:inline-flex;align-items:center;gap:7px;border-radius:9px;padding:10px 14px;font-weight:700;border:1px solid var(--border);background:#fff}.btn-primary{background:var(--primary);border-color:var(--primary);color:#fff}.container{max-width:1180px;margin:auto;padding:28px 20px}.hero{padding:48px 0 26px}.hero h1{font-size:40px;line-height:1.1;margin:0 0 12px}.hero p{color:var(--muted);font-size:18px;max-width:760px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.card{background:#fff;border:1px solid var(--border);border-radius:14px;padding:18px}.card h3{margin-top:0}.muted{color:var(--muted)}.filters{display:flex;gap:10px;margin-bottom:18px}.filters input{flex:1;border:1px solid #d1d5db;border-radius:9px;padding:11px}.badge{display:inline-flex;border-radius:999px;padding:4px 8px;background:#ede9fe;color:var(--primary);font-size:12px;font-weight:800}.pagination{margin-top:20px}.auth-actions{display:flex;gap:8px;align-items:center}.footer{margin-top:50px;background:#24183f;color:#fff}.footer-inner{max-width:1180px;margin:auto;padding:28px 20px;display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}.flash{padding:12px 14px;border-radius:9px;margin-bottom:16px;background:#ecfdf5;border:1px solid #bbf7d0;color:#166534}@media(max-width:850px){.nav{align-items:flex-start;flex-wrap:wrap}.nav-links{width:100%;overflow:auto;white-space:nowrap;flex-wrap:nowrap}.grid{grid-template-columns:1fr 1fr}.hero h1{font-size:32px}}@media(max-width:600px){.grid{grid-template-columns:1fr}.auth-actions{width:100%}}
</style>
</head>
<body>
<header class="site-header"><nav class="nav"><a class="brand" href="{{ route('home') }}"><i class="fas fa-church"></i> COU Youth Platform</a><div class="nav-links"><a href="{{ route('public.news') }}">News</a><a href="{{ route('public.events') }}">Events</a><a href="{{ route('public.courses') }}">Courses</a><a href="{{ route('public.churches') }}">Church Locator</a><a href="{{ route('public.donate') }}">Donate</a><a href="{{ route('public.about') }}">About</a></div><div class="auth-actions">@auth<span class="muted">{{ auth()->user()->name }}</span><form method="post" action="{{ route('logout') }}">@csrf<button class="btn" type="submit">Logout</button></form>@else<a class="btn" href="{{ route('login') }}">Youth Login</a><a class="btn btn-primary" href="{{ route('register') }}">Sign Up</a>@endauth</div></nav></header>
<main class="container">@if(session('success'))<div class="flash">{{ session('success') }}</div>@endif @yield('content')</main>
<footer class="footer"><div class="footer-inner"><div><strong>Church of Uganda Youth Platform</strong><p>Connecting, discipling and empowering young people.</p></div><div>© {{ date('Y') }} Church of Uganda</div></div></footer>
</body></html>
