@extends('admin.layout')
@section('title','Church Locator')
@section('content')
<div class="page-head"><div><h1><i class="fas fa-location-dot"></i> Church Locator</h1><p>Manage church locations, service information and youth fellowship details.</p></div></div>

<div class="grid stats-grid">
    <div class="card stat-card stat-purple"><div class="stat-icon"><i class="fas fa-church"></i></div><div><strong>{{ number_format($stats['total']) }}</strong><span>Total locations</span></div></div>
    <div class="card stat-card stat-blue"><div class="stat-icon"><i class="fas fa-map-location-dot"></i></div><div><strong>{{ number_format($stats['mapped']) }}</strong><span>Mapped coordinates</span></div></div>
    <div class="card stat-card stat-green"><div class="stat-icon"><i class="fas fa-people-group"></i></div><div><strong>{{ number_format($stats['with_youth_times']) }}</strong><span>Youth fellowship times</span></div></div>
    <div class="card stat-card stat-orange"><div class="stat-icon"><i class="fas fa-address-book"></i></div><div><strong>{{ number_format($stats['with_contact']) }}</strong><span>With contact details</span></div></div>
</div>

<div class="card chart-card"><h3>Locations by church structure type</h3><div class="mini-bars">@php $max=max(1,(int)collect($chart)->max()); @endphp @forelse($chart as $label=>$value)<div class="mini-row"><span>{{ ucwords(str_replace('_',' ',$label)) }}</span><div class="mini-track"><i style="width:{{ ($value/$max)*100 }}%"></i></div><strong>{{ $value }}</strong></div>@empty<div class="empty">No locator data yet.</div>@endforelse</div></div>

<div class="card" style="margin-top:16px"><h3>Add church location</h3><form class="form-grid" method="post" action="{{route('admin.church-locations.store')}}">@csrf
<label>Church unit<select name="organisation_unit_id" required><option value="">Select unit</option>@foreach($units as $u)<option value="{{$u->id}}">{{$u->name}}</option>@endforeach</select></label>
<label>Name<input name="name" required placeholder="Church/location name"></label><label class="span-2">Address<input name="address" placeholder="Address"></label><label>Latitude<input name="latitude" placeholder="Latitude"></label><label>Longitude<input name="longitude" placeholder="Longitude"></label><label>Service times<input name="service_times" placeholder="Service times"></label><label>Youth fellowship times<input name="youth_fellowship_times" placeholder="Youth fellowship times"></label><label>Phone<input name="phone" placeholder="Phone"></label><label>Email<input name="email" placeholder="Email"></label><div class="span-2"><button class="btn btn-primary"><i class="fas fa-plus"></i> Add Location</button></div></form></div>

<div class="card table-card"><form class="filters" method="get" style="padding:15px"><input name="q" value="{{ request('q') }}" placeholder="Search church, address or contact"><select name="organisation_unit_id"><option value="">All units</option>@foreach($units as $u)<option value="{{$u->id}}" @selected((string)request('organisation_unit_id')===(string)$u->id)>{{$u->name}}</option>@endforeach</select><select name="coordinates"><option value="">All locations</option><option value="mapped" @selected(request('coordinates')==='mapped')>Mapped</option><option value="unmapped" @selected(request('coordinates')==='unmapped')>Needs coordinates</option></select><button class="btn btn-primary">Filter</button><a class="btn btn-light" href="{{ route('admin.church-locations.index') }}">Reset</a></form>
<div class="table-wrap"><table><thead><tr><th>Location</th><th>Church unit</th><th>Coordinates</th><th>Youth fellowship</th><th>Contact</th><th>Action</th></tr></thead><tbody>@forelse($items as $i)<tr><td><strong>{{$i->name}}</strong><small>{{$i->address ?: 'No address'}}</small></td><td>{{$i->organisationUnit?->name ?? '—'}}</td><td>@if($i->latitude!==null && $i->longitude!==null)<span class="badge badge-success">Mapped</span><small>{{$i->latitude}}, {{$i->longitude}}</small>@else<span class="badge badge-warning">Not mapped</span>@endif</td><td>{{$i->youth_fellowship_times ?: '—'}}</td><td>{{$i->phone ?: '—'}}<small>{{$i->email}}</small></td><td><form method="post" action="{{route('admin.church-locations.destroy',$i)}}" onsubmit="return confirm('Delete this location?')">@csrf @method('DELETE')<button class="btn btn-danger"><i class="fas fa-trash"></i> Delete</button></form></td></tr>@empty<tr><td colspan="6" class="empty">No church locations found.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{$items->links()}}</div></div>
@endsection

@push('styles')<style>
.stat-card{border-left:5px solid var(--primary)}.stat-purple{border-left-color:#7c3aed}.stat-blue{border-left-color:#2563eb}.stat-green{border-left-color:#16a34a}.stat-orange{border-left-color:#ea580c}.chart-card h3{margin-top:0}.mini-bars{display:grid;gap:12px}.mini-row{display:grid;grid-template-columns:160px 1fr 45px;gap:10px;align-items:center}.mini-track{height:10px;background:#eef2f7;border-radius:99px;overflow:hidden}.mini-track i{display:block;height:100%;background:var(--primary);border-radius:99px}
</style>@endpush
