@extends('admin.layout')
@section('title','Church Locator')
@section('content')
@php $max=max(1,(int)collect($chart)->max()); @endphp
<div class="page-head"><div><h1><i class="fas fa-location-dot"></i> Church Locator</h1><p>Manage church locations, service information and youth fellowship details.</p></div><button class="btn btn-primary" data-open-modal="location-create"><i class="fas fa-plus"></i> Add Location</button></div>
<div data-tabs>
<div class="tabs"><button class="tab active" data-tab-target="locations-overview"><i class="fas fa-chart-column"></i> Overview</button><button class="tab" data-tab-target="locations-list"><i class="fas fa-list"></i> Locations <span class="tab-count">{{ $items->total() }}</span></button></div>
<section id="locations-overview" class="tab-panel active"><div class="grid stats-grid"><div class="card stat-card stat-purple"><div class="stat-icon"><i class="fas fa-church"></i></div><div><strong>{{ number_format($stats['total']) }}</strong><span>Total locations</span></div></div><div class="card stat-card stat-blue"><div class="stat-icon"><i class="fas fa-map-location-dot"></i></div><div><strong>{{ number_format($stats['mapped']) }}</strong><span>Mapped coordinates</span></div></div><div class="card stat-card stat-green"><div class="stat-icon"><i class="fas fa-people-group"></i></div><div><strong>{{ number_format($stats['with_youth_times']) }}</strong><span>Youth fellowship times</span></div></div><div class="card stat-card stat-orange"><div class="stat-icon"><i class="fas fa-address-book"></i></div><div><strong>{{ number_format($stats['with_contact']) }}</strong><span>With contact details</span></div></div></div><div class="card"><h3 style="margin-top:0">Locations by church structure type</h3><div class="mini-bars">@forelse($chart as $label=>$value)<div class="mini-row"><span>{{ ucwords(str_replace('_',' ',$label)) }}</span><div class="mini-track"><i style="width:{{ ($value/$max)*100 }}%"></i></div><strong>{{ $value }}</strong></div>@empty<div class="empty">No locator data yet.</div>@endforelse</div></div></section>
<section id="locations-list" class="tab-panel"><div class="card"><form class="filters" method="get"><input name="q" value="{{ request('q') }}" placeholder="Search church, address or contact"><select name="organisation_unit_id"><option value="">All units</option>@foreach($units as $u)<option value="{{$u->id}}" @selected((string)request('organisation_unit_id')===(string)$u->id)>{{$u->name}}</option>@endforeach</select><select name="coordinates"><option value="">All locations</option><option value="mapped" @selected(request('coordinates')==='mapped')>Mapped</option><option value="unmapped" @selected(request('coordinates')==='unmapped')>Needs coordinates</option></select><button class="btn btn-primary"><i class="fas fa-search"></i> Filter</button><a class="btn btn-light" href="{{ route('admin.church-locations.index') }}#locations-list">Reset</a></form></div><div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Location</th><th>Church unit</th><th>Coordinates</th><th>Youth fellowship</th><th>Contact</th><th>Actions</th></tr></thead><tbody>@forelse($items as $i)<tr><td><strong>{{$i->name}}</strong><small>{{$i->address ?: 'No address'}}</small></td><td>{{$i->organisationUnit?->name ?? '—'}}</td><td>@if($i->latitude!==null && $i->longitude!==null)<span class="badge badge-success">Mapped</span><small>{{$i->latitude}}, {{$i->longitude}}</small>@else<span class="badge badge-warning">Not mapped</span>@endif</td><td>{{$i->youth_fellowship_times ?: '—'}}</td><td>{{$i->phone ?: '—'}}<small>{{$i->email}}</small></td><td><div class="actions"><button class="icon-btn" data-open-modal="location-view-{{ $i->id }}"><i class="fas fa-eye"></i></button><button class="icon-btn" data-open-modal="location-edit-{{ $i->id }}"><i class="fas fa-pen"></i></button><button class="icon-btn" data-open-modal="location-delete-{{ $i->id }}"><i class="fas fa-trash"></i></button></div></td></tr>@empty<tr><td colspan="6" class="empty">No church locations found.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{$items->withQueryString()->links()}}</div></div></section></div>

<div id="location-create" class="modal"><div class="modal-card"><div class="modal-head"><h2>Add Church Location</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="post" action="{{route('admin.church-locations.store')}}">@csrf<div class="form-grid"><label>Church unit<select name="organisation_unit_id" required><option value="">Select unit</option>@foreach($units as $u)<option value="{{$u->id}}">{{$u->name}}</option>@endforeach</select></label><label>Name<input name="name" required></label><label class="span-2">Address<input name="address"></label><label>Latitude<input name="latitude"></label><label>Longitude<input name="longitude"></label><label>Service times<input name="service_times"></label><label>Youth fellowship times<input name="youth_fellowship_times"></label><label>Phone<input name="phone"></label><label>Email<input name="email" type="email"></label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-floppy-disk"></i> Save Location</button></div></form></div></div>

@foreach($items as $i)
<div id="location-view-{{ $i->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>{{ $i->name }}</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><div class="detail-grid"><div class="detail-item"><span>Church Unit</span><strong>{{ $i->organisationUnit?->name ?: '—' }}</strong></div><div class="detail-item"><span>Address</span><strong>{{ $i->address ?: '—' }}</strong></div><div class="detail-item"><span>Latitude</span><strong>{{ $i->latitude ?? '—' }}</strong></div><div class="detail-item"><span>Longitude</span><strong>{{ $i->longitude ?? '—' }}</strong></div><div class="detail-item"><span>Service Times</span><strong>{{ $i->service_times ?: '—' }}</strong></div><div class="detail-item"><span>Youth Fellowship</span><strong>{{ $i->youth_fellowship_times ?: '—' }}</strong></div><div class="detail-item"><span>Phone</span><strong>{{ $i->phone ?: '—' }}</strong></div><div class="detail-item"><span>Email</span><strong>{{ $i->email ?: '—' }}</strong></div></div><div class="modal-actions"><button class="btn btn-light" data-close-modal>Close</button><button class="btn btn-primary" data-close-modal data-open-modal="location-edit-{{ $i->id }}"><i class="fas fa-pen"></i> Edit</button></div></div></div>
<div id="location-edit-{{ $i->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>Edit Church Location</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="post" action="{{route('admin.church-locations.update',$i)}}">@csrf @method('PUT')<div class="form-grid"><label>Church unit<select name="organisation_unit_id" required>@foreach($units as $u)<option value="{{$u->id}}" @selected($i->organisation_unit_id==$u->id)>{{$u->name}}</option>@endforeach</select></label><label>Name<input name="name" value="{{ $i->name }}" required></label><label class="span-2">Address<input name="address" value="{{ $i->address }}"></label><label>Latitude<input name="latitude" value="{{ $i->latitude }}"></label><label>Longitude<input name="longitude" value="{{ $i->longitude }}"></label><label>Service times<input name="service_times" value="{{ $i->service_times }}"></label><label>Youth fellowship times<input name="youth_fellowship_times" value="{{ $i->youth_fellowship_times }}"></label><label>Phone<input name="phone" value="{{ $i->phone }}"></label><label>Email<input name="email" type="email" value="{{ $i->email }}"></label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-floppy-disk"></i> Update Location</button></div></form></div></div>
<div id="location-delete-{{ $i->id }}" class="modal"><div class="modal-card small"><div class="modal-head"><h2>Delete Location?</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><p class="danger-copy">Delete <strong>{{ $i->name }}</strong>? This action cannot be undone.</p><form method="post" action="{{route('admin.church-locations.destroy',$i)}}">@csrf @method('DELETE')<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-danger"><i class="fas fa-trash"></i> Delete</button></div></form></div></div>
@endforeach
@endsection
@push('styles')<style>.stat-card{border-left:5px solid var(--primary)}.stat-purple{border-left-color:#7c3aed}.stat-blue{border-left-color:#2563eb}.stat-green{border-left-color:#16a34a}.stat-orange{border-left-color:#ea580c}.mini-bars{display:grid;gap:12px}.mini-row{display:grid;grid-template-columns:160px 1fr 45px;gap:10px;align-items:center}.mini-track{height:10px;background:#eef2f7;border-radius:99px;overflow:hidden}.mini-track i{display:block;height:100%;background:var(--primary);border-radius:99px}</style>@endpush
