@extends('admin.layout')
@section('title','Page Content')
@section('content')
<div class="page-head"><h1><i class="fas fa-pager"></i> Page Content</h1><p>Slides & cards for page: <strong>{{ $page }}</strong></p></div>
<form method="GET" action="{{ route('admin.page-content.index') }}" class="toolbar"><div class="filters"><select name="page"><option value="home" @selected($page==='home')>home</option><option value="about" @selected($page==='about')>about</option><option value="donate" @selected($page==='donate')>donate</option></select><button class="btn btn-light" type="submit">Filter</button></div><div class="actions"><button type="button" class="btn btn-primary" data-open-modal="addSlideModal"><i class="fas fa-plus"></i> Add Slide</button><button type="button" class="btn btn-primary" data-open-modal="addCardModal"><i class="fas fa-plus"></i> Add Card</button></div></form>
<div data-tabs><div class="tabs"><button class="tab active" data-tab-target="tabSlides">Slides <span class="tab-count">{{ $slides->count() }}</span></button><button class="tab" data-tab-target="tabCards">Cards <span class="tab-count">{{ $cards->count() }}</span></button></div>
<div class="tab-panel active" id="tabSlides"><div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Media</th><th>Title</th><th>Link</th><th>Order</th><th>Status</th><th>Actions</th></tr></thead><tbody>
@foreach($slides as $s)<tr><td>@if($s->media_path)@if($s->media_type==='video')<video src="{{ asset('storage/'.$s->media_path) }}" width="120" controls></video>@else<img src="{{ asset('storage/'.$s->media_path) }}" width="120" alt="">@endif @else — @endif</td><td>{{ $s->title }}<small>{{ $s->subtitle }}</small></td><td>{{ $s->link_url }}</td><td>{{ $s->sort_order }}</td><td><span class="badge {{ $s->is_active?'badge-success':'badge-warning' }}">{{ $s->is_active?'Active':'Hidden' }}</span></td><td><form method="POST" action="{{ route('admin.page-content.slides.destroy',$s) }}">@csrf @method('DELETE')<button class="btn btn-danger" type="submit">Delete</button></form></td></tr>@endforeach
</tbody></table></div></div></div>
<div class="tab-panel" id="tabCards"><div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Icon/Image</th><th>Title</th><th>Link</th><th>Order</th><th>Status</th><th>Actions</th></tr></thead><tbody>
@foreach($cards as $c)<tr><td><span class="card-icon-preview"><i class="fas {{ $c->icon ?? 'fa-star' }}"></i></span>@if($c->image_path)<img src="{{ asset('storage/'.$c->image_path) }}" width="80" alt="">@endif</td><td>{{ $c->title }}<small>{{ \Str::limit($c->body,80) }}</small></td><td>{{ $c->link_url }}</td><td>{{ $c->sort_order }}</td><td><span class="badge {{ $c->is_active?'badge-success':'badge-warning' }}">{{ $c->is_active?'Active':'Hidden' }}</span></td><td><form method="POST" action="{{ route('admin.page-content.cards.destroy',$c) }}">@csrf @method('DELETE')<button class="btn btn-danger" type="submit">Delete</button></form></td></tr>@endforeach
</tbody></table></div></div></div></div>
<div class="modal" id="addSlideModal"><div class="modal-card"><div class="modal-head"><h2>Add Slide</h2><button class="icon-btn" data-close-modal>&times;</button></div><form method="POST" action="{{ route('admin.page-content.slides.store') }}" enctype="multipart/form-data"><div class="form-grid">@csrf<input type="hidden" name="page" value="{{ $page }}"><label>Title<input name="title" placeholder="e.g. Youth Sunday Celebration" maxlength="180"></label><label>Subtitle<input name="subtitle" placeholder="e.g. Join us this Sunday at 9am" maxlength="255"></label><label>Media type<select name="media_type"><option value="image">image</option><option value="video">video</option></select></label><label>Link URL<input name="link_url" placeholder="https://example.com/event"></label><label>Sort order<input type="number" name="sort_order" placeholder="0" value="0"></label><label>Upload<input type="file" name="media_file" accept="image/*,video/*"></label><label class="span-2">Or media path<input name="media_path" placeholder="slides/example.jpg"></label><label class="span-2 checkbox"><input type="checkbox" name="is_active" value="1" checked> Active</label></div><div class="modal-actions"><button class="btn btn-light" data-close-modal type="button">Cancel</button><button class="btn btn-primary" type="submit">Save</button></div></form></div></div>
<div class="modal" id="addCardModal"><div class="modal-card"><div class="modal-head"><h2>Add Card</h2><button class="icon-btn" data-close-modal>&times;</button></div><form method="POST" action="{{ route('admin.page-content.cards.store') }}" enctype="multipart/form-data"><div class="form-grid">@csrf<input type="hidden" name="page" value="{{ $page }}"><label>Title<input name="title" placeholder="e.g. Worship Night"></label><label>Link URL<input name="link_url" placeholder="https://example.com/worship"></label><label class="span-2">Body<textarea name="body" placeholder="Short card description..."></textarea></label><label>Icon (FA class)<input name="icon" id="cardIconInput" placeholder="fa-star" oninput="document.getElementById('cardIconPreview').className='fas '+this.value"></label><label>Image upload<input type="file" name="image_file" accept="image/*"></label><label>Image path<input name="image_path" placeholder="cards/example.jpg"></label><label>Sort order<input type="number" name="sort_order" placeholder="0" value="0"></label><label class="span-2">Preview: <i id="cardIconPreview" class="fas fa-star"></i> <img id="cardImgPreview" width="80" alt="" onload="this.style.display='block'" style="display:none"></label><label class="span-2 checkbox"><input type="checkbox" name="is_active" value="1" checked> Active</label></div><div class="modal-actions"><button class="btn btn-light" data-close-modal type="button">Cancel</button><button class="btn btn-primary" type="submit">Save</button></div></form></div></div>
@endsection
@push('scripts')<script>document.querySelector('input[name=image_file]')?.addEventListener('change',e=>{const f=e.target.files[0];if(f){const u=URL.createObjectURL(f);const img=document.getElementById('cardImgPreview');img.src=u;img.style.display='block';}});</script>@endpush
