@extends('admin.layout')
@section('title','Guardian Consents')
@section('content')
@php $max=max(1,(int)collect($chart)->max()); @endphp
<div class="page-head"><div><h1><i class="fas fa-shield-heart"></i> Guardian Consents</h1><p>Review and manage safeguarding consent submissions.</p></div></div>
<div data-tabs>
<div class="tabs"><button class="tab active" data-tab-target="consents-overview"><i class="fas fa-chart-column"></i> Overview</button><button class="tab" data-tab-target="consents-list"><i class="fas fa-list"></i> Consents <span class="tab-count">{{ $consents->total() }}</span></button></div>
<section id="consents-overview" class="tab-panel active"><div class="grid stats-grid"><div class="card stat-card stat-purple"><div class="stat-icon"><i class="fas fa-file-signature"></i></div><div><strong>{{ number_format($stats['total']) }}</strong><span>Total consents</span></div></div><div class="card stat-card stat-orange"><div class="stat-icon"><i class="fas fa-hourglass-half"></i></div><div><strong>{{ number_format($stats['pending']) }}</strong><span>Pending</span></div></div><div class="card stat-card stat-green"><div class="stat-icon"><i class="fas fa-circle-check"></i></div><div><strong>{{ number_format($stats['approved']) }}</strong><span>Approved</span></div></div><div class="card stat-card stat-red"><div class="stat-icon"><i class="fas fa-circle-xmark"></i></div><div><strong>{{ number_format($stats['rejected']) }}</strong><span>Rejected</span></div></div></div><div class="card"><h3 style="margin-top:0">Consent status distribution</h3><div class="mini-bars">@forelse($chart as $label=>$value)<div class="mini-row"><span>{{ ucfirst($label) }}</span><div class="mini-track"><i style="width:{{ ($value/$max)*100 }}%"></i></div><strong>{{ $value }}</strong></div>@empty<div class="empty">No consent data yet.</div>@endforelse</div></div></section>
<section id="consents-list" class="tab-panel"><div class="card"><form class="filters" method="get"><input name="q" value="{{ request('q') }}" placeholder="Search guardian, youth, email or phone"><select name="status"><option value="">All statuses</option>@foreach(['pending','approved','rejected'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ ucfirst($s) }}</option>@endforeach</select><button class="btn btn-primary"><i class="fas fa-search"></i> Filter</button><a class="btn btn-light" href="{{ route('admin.guardian-consents.index') }}#consents-list">Reset</a></form></div><div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Youth</th><th>Guardian</th><th>Contact</th><th>Status</th><th>Submitted</th><th>Actions</th></tr></thead><tbody>@forelse($consents as $c)<tr><td><strong>{{ $c->user?->name ?? 'User' }}</strong><small>{{ $c->user?->email }}</small></td><td>{{ $c->guardian_name }}</td><td>{{ $c->guardian_phone ?? '—' }}<small>{{ $c->guardian_email }}</small></td><td><span class="badge {{ $c->status==='approved'?'badge-success':($c->status==='rejected'?'badge-danger':'badge-warning') }}">{{ ucfirst($c->status) }}</span></td><td>{{ optional($c->created_at)->format('d M Y H:i') }}</td><td><div class="actions"><button class="icon-btn" data-open-modal="consent-view-{{ $c->id }}"><i class="fas fa-eye"></i></button>@if($c->status==='pending')<button class="icon-btn" data-open-modal="consent-approve-{{ $c->id }}"><i class="fas fa-check"></i></button><button class="icon-btn" data-open-modal="consent-reject-{{ $c->id }}"><i class="fas fa-xmark"></i></button>@endif</div></td></tr>@empty<tr><td colspan="6" class="empty">No guardian consents found.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $consents->withQueryString()->links() }}</div></div></section></div>
@foreach($consents as $c)
<div id="consent-view-{{ $c->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>Guardian Consent</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><div class="detail-grid"><div class="detail-item"><span>Youth</span><strong>{{ $c->user?->name ?? 'User' }}</strong></div><div class="detail-item"><span>Status</span><strong>{{ ucfirst($c->status) }}</strong></div><div class="detail-item"><span>Guardian</span><strong>{{ $c->guardian_name }}</strong></div><div class="detail-item"><span>Relationship</span><strong>{{ $c->guardian_relationship ?? '—' }}</strong></div><div class="detail-item"><span>Phone</span><strong>{{ $c->guardian_phone ?: '—' }}</strong></div><div class="detail-item"><span>Email</span><strong>{{ $c->guardian_email ?: '—' }}</strong></div><div class="detail-item"><span>Submitted</span><strong>{{ optional($c->created_at)->format('d M Y H:i') }}</strong></div><div class="detail-item"><span>Verified</span><strong>{{ optional($c->verified_at)->format('d M Y H:i') ?: '—' }}</strong></div></div><div class="modal-actions"><button class="btn btn-light" data-close-modal>Close</button>@if($c->status==='pending')<button class="btn btn-primary" data-close-modal data-open-modal="consent-approve-{{ $c->id }}">Approve</button><button class="btn btn-danger" data-close-modal data-open-modal="consent-reject-{{ $c->id }}">Reject</button>@endif</div></div></div>
<div id="consent-approve-{{ $c->id }}" class="modal"><div class="modal-card small"><div class="modal-head"><h2>Approve Consent?</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><p>Approve guardian consent submitted by <strong>{{ $c->guardian_name }}</strong> for {{ $c->user?->name ?? 'this user' }}?</p><form method="post" action="{{ route('admin.guardian-consents.approve',$c) }}">@csrf<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-check"></i> Approve</button></div></form></div></div>
<div id="consent-reject-{{ $c->id }}" class="modal"><div class="modal-card small"><div class="modal-head"><h2>Reject Consent?</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><p class="danger-copy">Reject guardian consent submitted by <strong>{{ $c->guardian_name }}</strong>? The youth account will remain unverified for safeguarding.</p><form method="post" action="{{ route('admin.guardian-consents.reject',$c) }}">@csrf<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-danger"><i class="fas fa-xmark"></i> Reject</button></div></form></div></div>
@endforeach
@endsection
@push('styles')<style>.stat-card{border-left:5px solid var(--primary)}.stat-purple{border-left-color:#7c3aed}.stat-orange{border-left-color:#ea580c}.stat-green{border-left-color:#16a34a}.stat-red{border-left-color:#dc2626}.mini-bars{display:grid;gap:12px}.mini-row{display:grid;grid-template-columns:110px 1fr 45px;gap:10px;align-items:center}.mini-track{height:10px;background:#eef2f7;border-radius:99px;overflow:hidden}.mini-track i{display:block;height:100%;background:var(--primary);border-radius:99px}</style>@endpush
