@extends('admin.layout')
@section('title','Payment Gateways | COU Youth CMS')
@section('content')
<div class="page-head"><div><h1><i class="fas fa-credit-card"></i> Payment Gateways</h1><p>Configure payment providers, credentials, callbacks and operating mode.</p></div><button type="button" class="btn btn-primary" data-open-modal="gateway-create-modal"><i class="fas fa-plus"></i> Add Gateway</button></div>
<div data-tabs>
<div class="tabs"><button class="tab active" data-tab-target="gateways-overview"><i class="fas fa-chart-column"></i> Overview</button><button class="tab" data-tab-target="gateways-list"><i class="fas fa-list"></i> Gateways <span class="tab-count">{{ $items->total() }}</span></button></div>
<section id="gateways-overview" class="tab-panel active"><div class="grid stats-grid gateway-stats"><div class="card stat-card stat-purple"><div class="stat-icon"><i class="fas fa-wallet"></i></div><div><strong>{{ number_format($stats['total']??0) }}</strong><span>Total gateways</span></div></div><div class="card stat-card stat-green"><div class="stat-icon"><i class="fas fa-circle-check"></i></div><div><strong>{{ number_format($stats['enabled']??0) }}</strong><span>Enabled</span></div></div><div class="card stat-card stat-blue"><div class="stat-icon"><i class="fas fa-satellite-dish"></i></div><div><strong>{{ number_format($stats['live']??0) }}</strong><span>Live mode</span></div></div><div class="card stat-card stat-orange"><div class="stat-icon"><i class="fas fa-flask"></i></div><div><strong>{{ number_format($stats['test']??0) }}</strong><span>Test mode</span></div></div></div><div class="card gateway-note"><div class="gateway-note-icon"><i class="fas fa-shield-halved"></i></div><div><strong>Credential security</strong><p>API credentials and webhook secrets are encrypted at rest and are never displayed back in the CMS. Leave secret fields blank while editing to retain saved values.</p></div></div></section>
<section id="gateways-list" class="tab-panel"><form method="GET" action="{{ route('admin.payment-gateways.index') }}" class="card gateway-filters"><div class="filter-search"><i class="fas fa-magnifying-glass"></i><input type="search" name="q" value="{{ $filters['q']??'' }}" placeholder="Search name, provider, slug or currency"></div><select name="status"><option value="">All statuses</option><option value="enabled" @selected(($filters['status']??'')==='enabled')>Enabled</option><option value="disabled" @selected(($filters['status']??'')==='disabled')>Disabled</option></select><select name="mode"><option value="">All modes</option><option value="live" @selected(($filters['mode']??'')==='live')>Live</option><option value="test" @selected(($filters['mode']??'')==='test')>Test</option></select><button class="btn btn-primary"><i class="fas fa-filter"></i> Filter</button><a href="{{ route('admin.payment-gateways.index') }}#gateways-list" class="btn btn-light">Reset</a></form><div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Gateway</th><th>Provider</th><th>Currency</th><th>Mode</th><th>Status</th><th>Order</th><th>Actions</th></tr></thead><tbody>@forelse($items as $gateway)<tr><td><strong>{{ $gateway->name }}</strong><small>{{ $gateway->slug }}</small></td><td>{{ $gateway->provider }}</td><td><span class="badge">{{ strtoupper($gateway->currency) }}</span></td><td><span class="badge {{ $gateway->is_test_mode?'badge-warning':'badge-success' }}">{{ $gateway->is_test_mode?'Test':'Live' }}</span></td><td><span class="badge {{ $gateway->is_enabled?'badge-success':'' }}">{{ $gateway->is_enabled?'Enabled':'Disabled' }}</span></td><td>{{ number_format((int)$gateway->sort_order) }}</td><td><div class="actions"><button class="icon-btn" data-open-modal="gateway-view-{{ $gateway->id }}"><i class="fas fa-eye"></i></button><button class="icon-btn" data-open-modal="gateway-edit-{{ $gateway->id }}"><i class="fas fa-pen"></i></button><button class="icon-btn" data-open-modal="gateway-delete-{{ $gateway->id }}"><i class="fas fa-trash"></i></button></div></td></tr>@empty<tr><td colspan="7" class="empty">No payment gateways found.</td></tr>@endforelse</tbody></table></div>@if($items->hasPages())<div class="pagination">{{ $items->withQueryString()->links() }}</div>@endif</div></section>
</div>

<div class="modal" id="gateway-create-modal"><div class="modal-card large"><div class="modal-head"><div><h2><i class="fas fa-plus-circle"></i> Add Payment Gateway</h2><p>Start in test mode until integration is verified.</p></div><button type="button" class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="POST" action="{{ route('admin.payment-gateways.store') }}">@csrf @include('admin.payment_gateways.partials.form',['gateway'=>null,'settings'=>[],'submitLabel'=>'Add Gateway','submitIcon'=>'fa-plus'])</form></div></div>

@foreach($items as $gateway)
@php $gatewaySettings=is_array($gateway->settings)?$gateway->settings:[]; @endphp
<div id="gateway-view-{{ $gateway->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>{{ $gateway->name }}</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><div class="detail-grid"><div class="detail-item"><span>Provider</span><strong>{{ $gateway->provider }}</strong></div><div class="detail-item"><span>Slug</span><strong>{{ $gateway->slug }}</strong></div><div class="detail-item"><span>Currency</span><strong>{{ strtoupper($gateway->currency) }}</strong></div><div class="detail-item"><span>Mode</span><strong>{{ $gateway->is_test_mode?'Test':'Live' }}</strong></div><div class="detail-item"><span>Status</span><strong>{{ $gateway->is_enabled?'Enabled':'Disabled' }}</strong></div><div class="detail-item"><span>Sort order</span><strong>{{ $gateway->sort_order }}</strong></div><div class="detail-item span-2"><span>Base URL</span><strong>{{ $gatewaySettings['base_url']??'Provider default' }}</strong></div><div class="detail-item span-2"><span>Callback URL</span><strong>{{ $gatewaySettings['callback_url']??'—' }}</strong></div><div class="detail-item span-2"><span>Webhook URL</span><strong>{{ $gatewaySettings['webhook_url']??'—' }}</strong></div><div class="detail-item span-2"><span>Credentials</span><strong><i class="fas fa-lock"></i> Encrypted and hidden</strong></div></div><div class="modal-actions"><button class="btn btn-light" data-close-modal>Close</button><button class="btn btn-primary" data-close-modal data-open-modal="gateway-edit-{{ $gateway->id }}"><i class="fas fa-pen"></i> Edit</button></div></div></div>
<div class="modal" id="gateway-edit-{{ $gateway->id }}"><div class="modal-card large"><div class="modal-head"><div><h2><i class="fas fa-pen-to-square"></i> Edit {{ $gateway->name }}</h2><p>Saved credentials remain encrypted.</p></div><button type="button" class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="POST" action="{{ route('admin.payment-gateways.update',$gateway) }}">@csrf @method('PUT') @include('admin.payment_gateways.partials.form',['gateway'=>$gateway,'settings'=>$gatewaySettings,'submitLabel'=>'Save Changes','submitIcon'=>'fa-floppy-disk'])</form></div></div>
<div id="gateway-delete-{{ $gateway->id }}" class="modal"><div class="modal-card small"><div class="modal-head"><h2>Delete Payment Gateway?</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><p class="danger-copy">Delete <strong>{{ $gateway->name }}</strong>? Confirm only if the gateway is no longer required and has no protected dependent records.</p><form method="POST" action="{{ route('admin.payment-gateways.destroy',$gateway) }}">@csrf @method('DELETE')<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-danger"><i class="fas fa-trash"></i> Delete</button></div></form></div></div>
@endforeach
@endsection
@push('styles')<style>.gateway-stats .stat-card{min-height:92px;border-left:5px solid var(--primary)}.stat-purple{border-left-color:#7c3aed!important}.stat-green{border-left-color:#16a34a!important}.stat-blue{border-left-color:#2563eb!important}.stat-orange{border-left-color:#ea580c!important}.gateway-note{display:flex;align-items:flex-start;gap:14px;border-left:4px solid var(--primary)}.gateway-note-icon{width:42px;height:42px;border-radius:10px;display:grid;place-items:center;background:#ede9fe;color:var(--primary)}.gateway-note p{margin:5px 0 0;color:var(--muted)}.gateway-filters{display:grid;grid-template-columns:minmax(260px,2fr) minmax(150px,1fr) minmax(150px,1fr) auto auto;gap:10px;align-items:center}.gateway-filters input,.gateway-filters select{width:100%;border:1px solid #d1d5db;border-radius:9px;padding:10px;background:#fff}.filter-search{position:relative}.filter-search i{position:absolute;left:12px;top:50%;transform:translateY(-50%);color:#9ca3af}.filter-search input{padding-left:36px}@media(max-width:900px){.gateway-filters{grid-template-columns:1fr 1fr}.filter-search{grid-column:1/-1}}@media(max-width:640px){.gateway-filters{grid-template-columns:1fr}.filter-search{grid-column:auto}}</style>@endpush
