@extends('admin.layout')
@section('title','Financial Reports')
@section('content')
<div class="page-head"><div><h1><i class="fas fa-chart-line"></i> Financial Reports</h1><p>Track membership collections and donations by reporting period.</p></div></div>
<div class="card"><form class="filters" method="GET"><label>From<input type="date" name="from" value="{{ $from->format('Y-m-d') }}"></label><label>To<input type="date" name="to" value="{{ $to->format('Y-m-d') }}"></label><button class="btn btn-primary">Apply</button><button class="btn btn-light" type="button" onclick="window.print()"><i class="fas fa-print"></i> Print / PDF</button></form></div>
<div class="grid stats-grid" style="margin-top:16px"><div class="card stat-card"><span class="stat-icon"><i class="fas fa-coins"></i></span><div><strong>UGX {{ number_format($membershipCollected) }}</strong><span>Membership fees</span></div></div><div class="card stat-card"><span class="stat-icon"><i class="fas fa-receipt"></i></span><div><strong>{{ $membershipCount }}</strong><span>Membership payments</span></div></div><div class="card stat-card"><span class="stat-icon"><i class="fas fa-hand-holding-heart"></i></span><div><strong>UGX {{ number_format($donations) }}</strong><span>Donations</span></div></div><div class="card stat-card"><span class="stat-icon"><i class="fas fa-hashtag"></i></span><div><strong>{{ $donationCount }}</strong><span>Donation transactions</span></div></div></div>
<div class="grid" style="grid-template-columns:2fr 1fr"><div class="card"><h3>Summary</h3><div class="table-wrap"><table style="min-width:0"><thead><tr><th>Income source</th><th>Transactions</th><th>Total</th></tr></thead><tbody><tr><td>Membership fees</td><td>{{ $membershipCount }}</td><td>UGX {{ number_format($membershipCollected) }}</td></tr><tr><td>Donations</td><td>{{ $donationCount }}</td><td>UGX {{ number_format($donations) }}</td></tr><tr><td><strong>Total income</strong></td><td>{{ $membershipCount + $donationCount }}</td><td><strong>UGX {{ number_format($membershipCollected + $donations) }}</strong></td></tr></tbody></table></div></div><div class="card"><h3>Membership by payment method</h3>@forelse($byMethod as $m)<div style="display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid var(--border)"><span>{{ $m->method }}<small style="display:block;color:var(--muted)">{{ $m->count }} payments</small></span><strong>{{ number_format((float)$m->total) }}</strong></div>@empty<p class="muted">No membership payments in this period.</p>@endforelse</div></div>
<style>@media print{.side,.top,.btn,.filters{display:none!important}.wrap{display:block}.main{padding:0}.card{box-shadow:none}.page-head{margin-top:0}}@media(max-width:900px){.grid[style]{grid-template-columns:1fr!important}}</style>
@endsection
