@extends('admin.layout')
@section('title','Moderation')
@section('content')
@php $max=max(1,(int)collect($chart)->max()); @endphp
<div class="page-head"><div><h1><i class="fas fa-shield-halved"></i> Moderation & Safety Reports</h1><p>Review community reports and track resolutions.</p></div></div>
<div data-tabs>
<div class="tabs"><button class="tab active" data-tab-target="moderation-overview"><i class="fas fa-chart-column"></i> Overview</button><button class="tab" data-tab-target="moderation-list"><i class="fas fa-list"></i> Reports <span class="tab-count">{{ $reports->total() }}</span></button><button class="tab" data-tab-target="moderation-comments"><i class="fas fa-comments"></i> Comments <span class="tab-count">{{ $comments->total() }}</span></button></div>
<section id="moderation-overview" class="tab-panel active"><div class="grid stats-grid"><div class="card stat-card stat-purple"><div class="stat-icon"><i class="fas fa-flag"></i></div><div><strong>{{ number_format($stats['total']) }}</strong><span>Total reports</span></div></div><div class="card stat-card stat-red"><div class="stat-icon"><i class="fas fa-circle-exclamation"></i></div><div><strong>{{ number_format($stats['open']) }}</strong><span>Open</span></div></div><div class="card stat-card stat-orange"><div class="stat-icon"><i class="fas fa-magnifying-glass"></i></div><div><strong>{{ number_format($stats['reviewing']) }}</strong><span>Reviewing</span></div></div><div class="card stat-card stat-green"><div class="stat-icon"><i class="fas fa-circle-check"></i></div><div><strong>{{ number_format($stats['resolved']) }}</strong><span>Resolved / dismissed</span></div></div></div><div class="card"><h3 style="margin-top:0">Reports by status</h3><div class="mini-bars">@forelse($chart as $label=>$value)<div class="mini-row"><span>{{ ucfirst($label) }}</span><div class="mini-track"><i style="width:{{ ($value/$max)*100 }}%"></i></div><strong>{{ $value }}</strong></div>@empty<div class="empty">No reports yet.</div>@endforelse</div></div></section>
<section id="moderation-list" class="tab-panel"><div class="card"><form class="filters" method="get"><input name="q" value="{{ request('q') }}" placeholder="Search reason, details or reporter"><select name="status"><option value="">All statuses</option>@foreach(['open','reviewing','resolved','dismissed'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ ucfirst($s) }}</option>@endforeach</select><button class="btn btn-primary"><i class="fas fa-search"></i> Filter</button><a class="btn btn-light" href="{{ route('admin.moderation.index') }}#moderation-list">Reset</a></form></div><div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Report</th><th>Reporter</th><th>Status</th><th>Submitted</th><th>Actions</th></tr></thead><tbody>@forelse($reports as $report)<tr><td><strong>{{ $report->reason }}</strong><small>{{ Str::limit($report->details,100) }}</small></td><td>{{ optional($report->reporter)->name ?? 'User' }}</td><td><span class="badge {{ $report->status==='resolved'?'badge-success':($report->status==='open'?'badge-danger':'badge-warning') }}">{{ ucfirst($report->status) }}</span></td><td>{{ $report->created_at->format('d M Y H:i') }}</td><td><div class="actions"><button class="icon-btn" data-open-modal="report-view-{{ $report->id }}"><i class="fas fa-eye"></i></button><button class="icon-btn" data-open-modal="report-review-{{ $report->id }}"><i class="fas fa-pen"></i></button></div></td></tr>@empty<tr><td colspan="5" class="empty">No moderation reports found.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $reports->withQueryString()->links() }}</div></div></section><section id="moderation-comments" class="tab-panel"><div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Comment</th><th>Author</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($comments as $comment)<tr><td><strong>{{ $comment->guest_name ?: optional($comment->user)->name }}</strong><small>{{ $comment->body }}</small></td><td>{{ optional($comment->user)->name ?? $comment->guest_name ?? "Guest" }}</td><td><span class="badge badge-warning">{{ ucfirst($comment->status) }}</span></td><td><div class="actions"><form method="POST" action="{{ route('admin.comments.approve',$comment) }}">@csrf<button class="icon-btn" title="Approve"><i class="fas fa-check"></i></button></form><form method="POST" action="{{ route('admin.comments.hide',$comment) }}">@csrf<button class="icon-btn" title="Hide"><i class="fas fa-eye-slash"></i></button></form><form method="POST" action="{{ route('admin.comments.destroy',$comment) }}">@csrf @method('DELETE')<button class="icon-btn" title="Delete"><i class="fas fa-trash"></i></button></form></div></td></tr>@empty<tr><td colspan="4" class="empty">No pending comments.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $comments->withQueryString()->links() }}</div></div></section></div>
@foreach($reports as $report)
<div id="report-view-{{ $report->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>Moderation Report</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><div class="detail-grid"><div class="detail-item"><span>Reason</span><strong>{{ $report->reason }}</strong></div><div class="detail-item"><span>Status</span><strong>{{ ucfirst($report->status) }}</strong></div><div class="detail-item"><span>Reporter</span><strong>{{ optional($report->reporter)->name ?? 'User' }}</strong></div><div class="detail-item"><span>Submitted</span><strong>{{ $report->created_at->format('d M Y H:i') }}</strong></div><div class="detail-item span-2"><span>Details</span><strong>{{ $report->details ?: '—' }}</strong></div><div class="detail-item span-2"><span>Resolution notes</span><strong>{{ $report->resolution_notes ?: '—' }}</strong></div></div><div class="modal-actions"><button class="btn btn-light" data-close-modal>Close</button><button class="btn btn-primary" data-close-modal data-open-modal="report-review-{{ $report->id }}"><i class="fas fa-pen"></i> Review</button></div></div></div>
<div id="report-review-{{ $report->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>Review Report</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="POST" action="{{ route('admin.moderation.resolve',$report) }}">@csrf @method('PUT')<div class="form-grid"><label>Status<select name="status"><option value="reviewing" @selected($report->status==='reviewing')>Reviewing</option><option value="resolved" @selected($report->status==='resolved')>Resolved</option><option value="dismissed" @selected($report->status==='dismissed')>Dismissed</option></select></label><label class="span-2">Resolution notes<textarea name="resolution_notes" rows="6">{{ $report->resolution_notes }}</textarea></label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-floppy-disk"></i> Save Review</button></div></form></div></div>
@endforeach
@endsection
@push('styles')<style>.stat-card{border-left:5px solid var(--primary)}.stat-purple{border-left-color:#7c3aed}.stat-red{border-left-color:#dc2626}.stat-orange{border-left-color:#ea580c}.stat-green{border-left-color:#16a34a}.mini-bars{display:grid;gap:12px}.mini-row{display:grid;grid-template-columns:100px 1fr 45px;gap:10px;align-items:center}.mini-track{height:10px;background:#eef2f7;border-radius:99px;overflow:hidden}.mini-track i{display:block;height:100%;background:var(--primary);border-radius:99px}</style>@endpush
