@extends('admin.layout')
@section('title','Prayer & Pastoral Support')
@section('content')
@php $maxStatus=max(1,(int)collect($statusCounts)->max()); @endphp
<div class="page-head"><div><h1><i class="fas fa-hands-praying"></i> Prayer & Pastoral Support</h1><p>Review prayer requests, pastoral follow-up and safeguarding referrals.</p></div></div>
<div data-tabs>
<div class="tabs"><button class="tab active" data-tab-target="prayer-overview"><i class="fas fa-chart-column"></i> Overview</button><button class="tab" data-tab-target="prayer-list"><i class="fas fa-list"></i> Requests <span class="tab-count">{{ $items->total() }}</span></button></div>
<section id="prayer-overview" class="tab-panel active"><div class="grid stats-grid"><div class="card stat-card stat-purple"><div class="stat-icon"><i class="fas fa-inbox"></i></div><div><strong>{{ number_format($stats['total']) }}</strong><span>Total requests</span></div></div><div class="card stat-card stat-blue"><div class="stat-icon"><i class="fas fa-hourglass-half"></i></div><div><strong>{{ number_format($stats['open']) }}</strong><span>Open cases</span></div></div><div class="card stat-card stat-green"><div class="stat-icon"><i class="fas fa-circle-check"></i></div><div><strong>{{ number_format($stats['resolved']) }}</strong><span>Resolved / closed</span></div></div><div class="card stat-card stat-red"><div class="stat-icon"><i class="fas fa-shield-heart"></i></div><div><strong>{{ number_format($stats['safeguarding']) }}</strong><span>Safeguarding review</span></div></div></div><div class="card"><h3 style="margin-top:0">Case status distribution</h3><div class="mini-chart">@foreach(['submitted'=>'Submitted','under_review'=>'Under review','referred'=>'Referred','resolved'=>'Resolved','closed'=>'Closed'] as $key=>$label)@php $count=(int)($statusCounts[$key]??0); @endphp<div class="chart-row"><span>{{ $label }}</span><div class="chart-track"><div class="chart-bar" style="width:{{ ($count/$maxStatus)*100 }}%"></div></div><strong>{{ $count }}</strong></div>@endforeach</div></div></section>
<section id="prayer-list" class="tab-panel"><div class="card"><form method="get" class="filters"><input type="search" name="q" value="{{ $filters['q'] }}" placeholder="Search subject, request or notes"><select name="status"><option value="">All statuses</option>@foreach(['submitted'=>'Submitted','under_review'=>'Under review','referred'=>'Referred','resolved'=>'Resolved','closed'=>'Closed'] as $value=>$label)<option value="{{ $value }}" @selected($filters['status']===$value)>{{ $label }}</option>@endforeach</select><select name="safeguarding"><option value="">All cases</option><option value="1" @selected($filters['safeguarding'])>Safeguarding review only</option></select><button class="btn btn-primary"><i class="fas fa-search"></i> Search</button><a class="btn btn-light" href="{{ route('admin.prayer.index') }}#prayer-list">Reset</a></form></div><div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Request</th><th>Visibility</th><th>Status</th><th>Safeguarding</th><th>Submitted</th><th>Actions</th></tr></thead><tbody>@forelse($items as $item)<tr><td><strong>{{ $item->subject }}</strong><small>{{ Str::limit($item->message,110) }}</small></td><td>{{ ucwords(str_replace('_',' ',$item->visibility)) }}</td><td><span class="badge {{ in_array($item->status,['resolved','closed'],true)?'badge-success':($item->status==='referred'?'badge-warning':'') }}">{{ ucwords(str_replace('_',' ',$item->status)) }}</span></td><td>@if($item->requires_safeguarding_review)<span class="badge badge-danger">Review required</span>@else<span class="badge">No flag</span>@endif</td><td>{{ optional($item->created_at)->format('d M Y H:i') }}</td><td><div class="actions"><button class="icon-btn" data-open-modal="prayer-view-{{ $item->id }}"><i class="fas fa-eye"></i></button><button class="icon-btn" data-open-modal="prayer-edit-{{ $item->id }}"><i class="fas fa-pen"></i></button></div></td></tr>@empty<tr><td colspan="6" class="empty">No prayer or pastoral requests found.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $items->withQueryString()->links() }}</div></div></section></div>
@foreach($items as $item)
<div id="prayer-view-{{ $item->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>{{ $item->subject }}</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div>@if($item->requires_safeguarding_review)<div class="alert alert-error"><i class="fas fa-shield-heart"></i> Safeguarding review required.</div>@endif<div class="detail-grid"><div class="detail-item"><span>Status</span><strong>{{ ucwords(str_replace('_',' ',$item->status)) }}</strong></div><div class="detail-item"><span>Visibility</span><strong>{{ ucwords(str_replace('_',' ',$item->visibility)) }}</strong></div><div class="detail-item"><span>Submitted</span><strong>{{ optional($item->created_at)->format('d M Y H:i') }}</strong></div><div class="detail-item"><span>Assigned to</span><strong>{{ $item->assigned_to ?: '—' }}</strong></div><div class="detail-item span-2"><span>Request</span><strong>{{ $item->message }}</strong></div><div class="detail-item span-2"><span>Restricted pastoral notes</span><strong>{{ $item->pastoral_notes ?: '—' }}</strong></div></div><div class="modal-actions"><button class="btn btn-light" data-close-modal>Close</button><button class="btn btn-primary" data-close-modal data-open-modal="prayer-edit-{{ $item->id }}"><i class="fas fa-pen"></i> Review</button></div></div></div>
<div id="prayer-edit-{{ $item->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>Review Prayer / Pastoral Case</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="post" action="{{ route('admin.prayer.update',$item) }}">@csrf @method('PUT')<div class="form-grid"><label>Status<select name="status" required>@foreach(['submitted'=>'Submitted','under_review'=>'Under review','referred'=>'Referred','resolved'=>'Resolved','closed'=>'Closed'] as $value=>$label)<option value="{{ $value }}" @selected($item->status===$value)>{{ $label }}</option>@endforeach</select></label><label class="span-2">Restricted pastoral notes<textarea name="pastoral_notes" rows="7">{{ $item->pastoral_notes }}</textarea></label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-floppy-disk"></i> Save Update</button></div></form></div></div>
@endforeach
@endsection
@push('styles')<style>.stat-card{border-left:5px solid var(--primary)}.stat-purple{border-left-color:#7c3aed}.stat-blue{border-left-color:#2563eb}.stat-green{border-left-color:#16a34a}.stat-red{border-left-color:#dc2626}.mini-chart{display:grid;gap:12px}.chart-row{display:grid;grid-template-columns:120px 1fr 42px;gap:10px;align-items:center}.chart-track{height:12px;background:#eef2f7;border-radius:99px;overflow:hidden}.chart-bar{height:100%;background:var(--primary);border-radius:99px}</style>@endpush
