@extends('admin.layout')
@section('title','Events')
@section('content')
@php $maxStatus=max(1,(int)collect($statusCounts)->max()); @endphp
<div class="page-head"><div><h1><i class="fas fa-calendar-days"></i> Events</h1><p>Manage youth events, publishing status and upcoming programmes.</p></div><button class="btn btn-primary" data-open-modal="event-create"><i class="fas fa-plus"></i> Add Event</button></div>

<div data-tabs>
    <div class="tabs">
        <button class="tab active" data-tab-target="events-overview"><i class="fas fa-chart-column"></i> Overview</button>
        <button class="tab" data-tab-target="events-list"><i class="fas fa-list"></i> Events <span class="tab-count">{{ $events->total() }}</span></button>
    </div>

    <section id="events-overview" class="tab-panel active">
        <div class="grid stats-grid event-stats">
            @foreach([['Total events',$stats['total'],'fa-calendar','#4b2e83'],['Published',$stats['published'],'fa-circle-check','#15803d'],['Upcoming',$stats['upcoming'],'fa-clock','#2563eb'],['Completed',$stats['completed'],'fa-flag-checkered','#b45309']] as [$label,$value,$icon,$tone])
                <div class="card stat-card event-stat" style="--tone:{{ $tone }}"><div class="stat-icon"><i class="fas {{ $icon }}"></i></div><div><strong>{{ number_format((int)$value) }}</strong><span>{{ $label }}</span></div></div>
            @endforeach
        </div>
        <div class="card"><h2 style="margin-top:0">Events by status</h2><div class="event-bars">@forelse($statusCounts as $status=>$total)<div class="event-bar-row"><span>{{ ucfirst($status) }}</span><div class="event-bar-track"><span style="width:{{ round(((int)$total/$maxStatus)*100) }}%"></span></div><strong>{{ $total }}</strong></div>@empty<div class="empty">No event data yet.</div>@endforelse</div></div>
    </section>

    <section id="events-list" class="tab-panel">
        <div class="card"><form method="get" class="filters"><input name="q" value="{{ $filters['q'] }}" placeholder="Search event, venue, category or speaker"><select name="status"><option value="">All statuses</option>@foreach(['draft','published','cancelled','completed'] as $status)<option value="{{ $status }}" @selected($filters['status']===$status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="btn btn-primary"><i class="fas fa-search"></i> Search</button><a class="btn btn-light" href="{{ route('admin.events.index') }}#events-list">Reset</a></form></div>
        <div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Event</th><th>Date</th><th>Venue</th><th>QR</th><th>Church Unit</th><th>Status</th><th>Actions</th></tr></thead><tbody>
        @forelse($events as $event)
            <tr><td><strong>{{ $event->title }}</strong><small>{{ $event->category ?: 'Uncategorised' }}</small></td><td>{{ optional($event->starts_at)->format('d M Y H:i') }}</td><td>{{ $event->venue ?: '—' }}</td><td>@php $regUrl = $event->qr_token ? route('public.event.register', $event->qr_token) : null; @endphp @if($regUrl)<a href="{{ $regUrl }}" target="_blank">Link</a><br><img src="https://api.qrserver.com/v1/create-qr-code/?size=120x120&data={{ urlencode($regUrl) }}" width="60" height="60" alt="QR"><br><button type="button" onclick="navigator.clipboard.writeText('{{ $regUrl }}')">Copy link</button>@else — @endif</td><td>{{ $event->organisationUnit?->name ?: 'All Church' }}</td><td><span class="badge {{ $event->status==='published'?'badge-success':($event->status==='cancelled'?'badge-danger':'badge-warning') }}">{{ ucfirst($event->status) }}</span></td><td><div class="actions"><button class="icon-btn" title="View" data-open-modal="event-view-{{ $event->id }}"><i class="fas fa-eye"></i></button><button class="icon-btn" title="Edit" data-open-modal="event-edit-{{ $event->id }}"><i class="fas fa-pen"></i></button><button class="icon-btn" title="Delete" data-open-modal="event-delete-{{ $event->id }}"><i class="fas fa-trash"></i></button></div></td></tr>
        @empty<tr><td colspan="6" class="empty">No events match your filters.</td></tr>@endforelse
        </tbody></table></div><div class="pagination">{{ $events->withQueryString()->links() }}</div></div>
    </section>
</div>

<div id="event-create" class="modal"><div class="modal-card"><div class="modal-head"><h2><i class="fas fa-plus"></i> Add Event</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="post" action="{{ route('admin.events.store') }}">@csrf<div class="form-grid"><label>Event name<input name="title" required placeholder="e.g. Youth Conference 2026"></label><label>Category<input name="category" placeholder="e.g. Conference"></label><label>Start date/time<input name="starts_at" type="datetime-local" required></label><label>End date/time<input name="ends_at" type="datetime-local"></label><label>Venue<input name="venue" placeholder="e.g. Main Hall"></label><label>Church unit ID<input name="organisation_unit_id" type="number" placeholder="e.g. 1"></label><label>Theme<input name="theme" placeholder="e.g. Rooted in Faith"></label><label>Speaker<input name="speaker" placeholder="e.g. John Doe"></label><label>Organizer<input name="organizer" placeholder="e.g. Youth Ministry"></label><label>Capacity<input name="capacity" type="number" min="1" placeholder="e.g. 200"></label><label>Fee<input name="fee" type="number" step="0.01" value="0" placeholder="e.g. 10000"></label><label>Currency<input name="currency" value="UGX" maxlength="3" required placeholder="UGX"></label><label>Status<select name="status"><option value="draft">Draft</option><option value="published">Published</option><option value="cancelled">Cancelled</option><option value="completed">Completed</option></select></label><label>External registration URL<input name="external_registration_url" placeholder="https://..."></label><label><input type="checkbox" name="allow_external_registration" value="1"> Allow external registration</label><label class="span-2">Description<textarea name="description" rows="4" placeholder="Event details..."></textarea></label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-floppy-disk"></i> Save Event</button></div></form></div></div>

@foreach($events as $event)
<div id="event-view-{{ $event->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>{{ $event->title }}</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><div class="detail-grid"><div class="detail-item"><span>Status</span><strong>{{ ucfirst($event->status) }}</strong></div><div class="detail-item"><span>Category</span><strong>{{ $event->category ?: '—' }}</strong></div><div class="detail-item"><span>Starts</span><strong>{{ optional($event->starts_at)->format('d M Y H:i') ?: '—' }}</strong></div><div class="detail-item"><span>Ends</span><strong>{{ optional($event->ends_at)->format('d M Y H:i') ?: '—' }}</strong></div><div class="detail-item"><span>Venue</span><strong>{{ $event->venue ?: '—' }}</strong></div><div class="detail-item"><span>Church Unit</span><strong>{{ $event->organisationUnit?->name ?: 'All Church' }}</strong></div><div class="detail-item"><span>Speaker</span><strong>{{ $event->speaker ?: '—' }}</strong></div><div class="detail-item"><span>Organizer</span><strong>{{ $event->organizer ?: '—' }}</strong></div><div class="detail-item"><span>Fee</span><strong>{{ $event->currency }} {{ number_format((float)$event->fee,2) }}</strong></div><div class="detail-item"><span>Capacity</span><strong>{{ $event->capacity ?: '—' }}</strong></div><div class="detail-item span-2"><span>Description</span><strong>{{ $event->description ?: 'No description.' }}</strong></div></div>@php $vUrl = $event->qr_token ? route('public.event.register', $event->qr_token) : null; @endphp @if($vUrl)<div class="detail-item span-2"><span>Registration link</span><strong style="word-break:break-all">{{ $vUrl }}</strong><br><img src="https://api.qrserver.com/v1/create-qr-code/?size=120x120&data={{ urlencode($vUrl) }}" width="120" height="120" alt="QR"><br><button type="button" class="btn btn-light" onclick="navigator.clipboard.writeText('{{ $vUrl }}')">Copy link</button></div>@endif<div class="modal-actions"><button class="btn btn-light" data-close-modal>Close</button><button class="btn btn-primary" data-close-modal data-open-modal="event-edit-{{ $event->id }}"><i class="fas fa-pen"></i> Edit</button></div></div></div>
<div id="event-edit-{{ $event->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>Edit Event</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="post" action="{{ route('admin.events.update',$event) }}">@csrf @method('PUT')<div class="form-grid"><label>Event name<input name="title" value="{{ $event->title }}" required></label><label>Category<input name="category" value="{{ $event->category }}"></label><label>Start date/time<input name="starts_at" type="datetime-local" value="{{ optional($event->starts_at)->format('Y-m-d\TH:i') }}" required></label><label>End date/time<input name="ends_at" type="datetime-local" value="{{ optional($event->ends_at)->format('Y-m-d\TH:i') }}"></label><label>Venue<input name="venue" value="{{ $event->venue }}"></label><label>Church unit ID<input name="organisation_unit_id" type="number" value="{{ $event->organisation_unit_id }}"></label><label>Theme<input name="theme" value="{{ $event->theme }}"></label><label>Speaker<input name="speaker" value="{{ $event->speaker }}"></label><label>Organizer<input name="organizer" value="{{ $event->organizer }}"></label><label>Capacity<input name="capacity" type="number" min="1" value="{{ $event->capacity }}"></label><label>Fee<input name="fee" type="number" step="0.01" value="{{ $event->fee }}"></label><label>Currency<input name="currency" value="{{ $event->currency }}" maxlength="3" required></label><label>Status<select name="status">@foreach(['draft','published','cancelled','completed'] as $status)<option value="{{ $status }}" @selected($event->status===$status)>{{ ucfirst($status) }}</option>@endforeach</select></label><label>External registration URL<input name="external_registration_url" value="{{ $event->external_registration_url }}" placeholder="https://..."></label><label><input type="checkbox" name="allow_external_registration" value="1" @checked($event->allow_external_registration)> Allow external registration</label><label class="span-2">Description<textarea name="description" rows="4" placeholder="Event details...">{{ $event->description }}</textarea></label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-floppy-disk"></i> Update Event</button></div></form></div></div>
<div id="event-delete-{{ $event->id }}" class="modal"><div class="modal-card small"><div class="modal-head"><h2>Delete Event?</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><p class="danger-copy">Delete <strong>{{ $event->title }}</strong>? This action cannot be undone.</p><form method="post" action="{{ route('admin.events.destroy',$event) }}">@csrf @method('DELETE')<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-danger"><i class="fas fa-trash"></i> Delete</button></div></form></div></div>
@endforeach

<style>.event-stats{grid-template-columns:repeat(4,minmax(0,1fr))}.event-stat{border-left:5px solid var(--tone)}.event-stat .stat-icon{color:var(--tone);background:#f6f4fb}.event-bars{display:grid;gap:12px}.event-bar-row{display:grid;grid-template-columns:90px 1fr 40px;gap:10px;align-items:center}.event-bar-row>span{font-size:13px;font-weight:700}.event-bar-track{height:12px;background:#f3f4f6;border-radius:99px;overflow:hidden}.event-bar-track span{display:block;height:100%;background:var(--primary);border-radius:99px}@media(max-width:900px){.event-stats{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.event-stats{grid-template-columns:1fr}}</style>
@endsection
