@extends('admin.layout')
@section('title','Courses')
@section('content')
<div class="page-head"><div><h1><i class="fas fa-book-bible"></i> Discipleship Courses</h1><p>Manage courses, lessons, visuals and publishing status.</p></div><button class="btn btn-primary" data-open-modal="course-create"><i class="fas fa-plus"></i> Add Course</button></div>
<div data-tabs>
<div class="tabs"><button class="tab active" data-tab-target="courses-overview"><i class="fas fa-chart-column"></i> Overview</button><button class="tab" data-tab-target="courses-list"><i class="fas fa-list"></i> Courses <span class="tab-count">{{ $courses->total() }}</span></button></div>
<section id="courses-overview" class="tab-panel active"><div class="grid stats-grid course-stats">@foreach([['Total courses',$stats['total'],'fa-book','#4b2e83'],['Published',$stats['published'],'fa-circle-check','#15803d'],['Draft',$stats['draft'],'fa-file-pen','#b45309'],['Lessons',$stats['lessons'],'fa-list-check','#2563eb']] as [$label,$value,$icon,$tone])<div class="card stat-card course-stat" style="--tone:{{ $tone }}"><div class="stat-icon"><i class="fas {{ $icon }}"></i></div><div><strong>{{ number_format((int)$value) }}</strong><span>{{ $label }}</span></div></div>@endforeach</div></section>
<section id="courses-list" class="tab-panel"><div class="card"><form method="get" class="filters"><input name="q" value="{{ $filters['q'] }}" placeholder="Search courses, description or age category"><select name="status"><option value="">All statuses</option><option value="published" @selected($filters['status']==='published')>Published</option><option value="draft" @selected($filters['status']==='draft')>Draft</option></select><button class="btn btn-primary"><i class="fas fa-search"></i> Search</button><a class="btn btn-light" href="{{ route('admin.courses.index') }}#courses-list">Reset</a></form></div>
<div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Visual</th><th>Course</th><th>Age</th><th>Lessons</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($courses as $course)<tr><td>@if($course->visual_type==='image' && $course->image_path)<img class="visual-thumb" src="{{ asset('storage/'.$course->image_path) }}" alt="">@else<span class="visual-icon"><i class="fas {{ $course->icon_class ?: 'fa-book-bible' }}"></i></span>@endif</td><td><strong>{{ $course->title }}</strong><small>{{ Str::limit($course->description ?: 'No description',80) }}</small></td><td>{{ ucwords(str_replace('_',' ',$course->age_category)) }}</td><td>{{ $course->lessons_count }}</td><td><span class="badge {{ $course->is_published?'badge-success':'badge-warning' }}">{{ $course->is_published?'Published':'Draft' }}</span></td><td><div class="actions"><button class="icon-btn" data-open-modal="course-view-{{ $course->id }}"><i class="fas fa-eye"></i></button><button class="icon-btn" data-open-modal="course-edit-{{ $course->id }}"><i class="fas fa-pen"></i></button><button class="icon-btn" data-open-modal="lesson-create-{{ $course->id }}"><i class="fas fa-list-check"></i></button><button class="icon-btn" data-open-modal="course-delete-{{ $course->id }}"><i class="fas fa-trash"></i></button></div></td></tr>@empty<tr><td colspan="6" class="empty">No courses match your filters.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $courses->withQueryString()->links() }}</div></div></section>
</div>

<div id="course-create" class="modal"><div class="modal-card"><div class="modal-head"><h2>Add Course</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="post" action="{{ route('admin.courses.store') }}" enctype="multipart/form-data" data-visual-form>@csrf<div class="form-grid"><label>Course title<input name="title" required></label><label>Age category<select name="age_category"><option value="all">All</option><option value="teen">Teen</option><option value="youth">Youth</option><option value="young_adult">Young Adult</option></select></label><label>Church unit<select name="organisation_unit_id"><option value="">All Church</option>@foreach($units as $u)<option value="{{ $u->id }}">{{ $u->name }}</option>@endforeach</select></label><label class="checkbox"><input type="checkbox" name="is_published" value="1"> Published</label><label class="span-2">Description<textarea name="description" rows="4"></textarea></label><label>Frontend card visual<select name="visual_type" data-visual-type><option value="icon">Use icon</option><option value="image">Use image</option></select></label><label data-icon-field>Font Awesome icon class<input name="icon_class" value="fa-book-bible" placeholder="fa-book-bible"><small>Example: fa-cross, fa-book-open, fa-people-group</small></label><label class="span-2" data-image-field style="display:none">Card image<input name="image" type="file" accept="image/png,image/jpeg,image/webp"></label><label class="span-2">Optional banner image<input name="banner" type="file" accept="image/png,image/jpeg,image/webp"><small>Used for larger frontend headers/detail sections.</small></label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-floppy-disk"></i> Save Course</button></div></form></div></div>

@foreach($courses as $course)
<div id="course-view-{{ $course->id }}" class="modal"><div class="modal-card large"><div class="modal-head"><h2>{{ $course->title }}</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div>@if($course->banner_path)<img class="course-banner" src="{{ asset('storage/'.$course->banner_path) }}" alt="{{ $course->title }} banner">@endif<div class="detail-grid"><div class="detail-item"><span>Status</span><strong>{{ $course->is_published?'Published':'Draft' }}</strong></div><div class="detail-item"><span>Frontend visual</span><strong>{{ ucfirst($course->visual_type ?: 'icon') }}</strong></div><div class="detail-item"><span>Age category</span><strong>{{ ucwords(str_replace('_',' ',$course->age_category)) }}</strong></div><div class="detail-item"><span>Lessons</span><strong>{{ $course->lessons_count }}</strong></div><div class="detail-item span-2"><span>Description</span><strong>{{ $course->description ?: 'No description.' }}</strong></div></div><h3>Lessons</h3><div class="table-wrap"><table><thead><tr><th>#</th><th>Lesson</th><th>Published</th><th>Action</th></tr></thead><tbody>@forelse($course->lessons as $lesson)<tr><td>{{ $lesson->position }}</td><td>{{ $lesson->title }}</td><td>{{ $lesson->is_published?'Yes':'No' }}</td><td><button class="icon-btn" data-close-modal data-open-modal="lesson-delete-{{ $lesson->id }}"><i class="fas fa-trash"></i></button></td></tr>@empty<tr><td colspan="4" class="empty">No lessons yet.</td></tr>@endforelse</tbody></table></div><div class="modal-actions"><button class="btn btn-light" data-close-modal>Close</button><button class="btn btn-primary" data-close-modal data-open-modal="lesson-create-{{ $course->id }}"><i class="fas fa-plus"></i> Add Lesson</button><button class="btn btn-primary" data-close-modal data-open-modal="course-edit-{{ $course->id }}"><i class="fas fa-pen"></i> Edit Course</button></div></div></div>
<div id="course-edit-{{ $course->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>Edit Course</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="post" action="{{ route('admin.courses.update',$course) }}" enctype="multipart/form-data" data-visual-form>@csrf @method('PUT')<div class="form-grid"><label>Course title<input name="title" value="{{ $course->title }}" required></label><label>Age category<select name="age_category">@foreach(['all','teen','youth','young_adult'] as $age)<option value="{{ $age }}" @selected($course->age_category===$age)>{{ ucwords(str_replace('_',' ',$age)) }}</option>@endforeach</select></label><label>Church unit<select name="organisation_unit_id"><option value="">All Church</option>@foreach($units as $u)<option value="{{ $u->id }}" @selected($course->organisation_unit_id==$u->id)>{{ $u->name }}</option>@endforeach</select></label><label class="checkbox"><input type="checkbox" name="is_published" value="1" @checked($course->is_published)> Published</label><label class="span-2">Description<textarea name="description" rows="4">{{ $course->description }}</textarea></label><label>Frontend card visual<select name="visual_type" data-visual-type><option value="icon" @selected(($course->visual_type ?: 'icon')==='icon')>Use icon</option><option value="image" @selected($course->visual_type==='image')>Use image</option></select></label><label data-icon-field>Font Awesome icon class<input name="icon_class" value="{{ $course->icon_class ?: 'fa-book-bible' }}"></label><label class="span-2" data-image-field>Replace card image<input name="image" type="file" accept="image/png,image/jpeg,image/webp">@if($course->image_path)<small>Current image is retained unless replaced.</small>@endif</label><label class="span-2">Replace banner image<input name="banner" type="file" accept="image/png,image/jpeg,image/webp">@if($course->banner_path)<small>Current banner is retained unless replaced.</small>@endif</label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-floppy-disk"></i> Update Course</button></div></form></div></div>
<div id="lesson-create-{{ $course->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>Add Lesson · {{ $course->title }}</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="post" action="{{ route('admin.courses.lessons.store',$course) }}">@csrf<div class="form-grid"><label>Lesson title<input name="title" required></label><label>Position<input name="position" type="number" min="1"></label><label class="span-2">Lesson content<textarea name="body" rows="6"></textarea></label><label class="span-2">Media URL<input name="media_url" type="url"></label><label class="checkbox"><input type="checkbox" name="is_published" value="1"> Published</label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-plus"></i> Add Lesson</button></div></form></div></div>
<div id="course-delete-{{ $course->id }}" class="modal"><div class="modal-card small"><div class="modal-head"><h2>Delete Course?</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><p class="danger-copy">Delete <strong>{{ $course->title }}</strong> and related lessons?</p><form method="post" action="{{ route('admin.courses.destroy',$course) }}">@csrf @method('DELETE')<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-danger"><i class="fas fa-trash"></i> Delete</button></div></form></div></div>
@foreach($course->lessons as $lesson)<div id="lesson-delete-{{ $lesson->id }}" class="modal"><div class="modal-card small"><div class="modal-head"><h2>Delete Lesson?</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><p class="danger-copy">Delete <strong>{{ $lesson->title }}</strong> from {{ $course->title }}?</p><form method="post" action="{{ route('admin.courses.lessons.destroy',[$course,$lesson]) }}">@csrf @method('DELETE')<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-danger">Delete</button></div></form></div></div>@endforeach
@endforeach
<style>.course-stats{grid-template-columns:repeat(4,minmax(0,1fr))}.course-stat{border-left:5px solid var(--tone)}.course-stat .stat-icon{color:var(--tone);background:#f6f4fb}.visual-thumb{width:52px;height:52px;object-fit:cover;border-radius:12px;border:1px solid var(--border)}.visual-icon{width:52px;height:52px;display:grid;place-items:center;border-radius:12px;background:#f1edfa;color:var(--primary);font-size:22px}.course-banner{width:100%;height:190px;object-fit:cover;border-radius:12px;margin-bottom:16px}@media(max-width:700px){.course-stats{grid-template-columns:1fr}}</style>
@endsection
@push('scripts')
<script>
(()=>{document.querySelectorAll('[data-visual-form]').forEach(form=>{const type=form.querySelector('[data-visual-type]');const icon=form.querySelector('[data-icon-field]');const image=form.querySelector('[data-image-field]');const sync=()=>{const useImage=type?.value==='image';if(icon)icon.style.display=useImage?'none':'';if(image)image.style.display=useImage?'':'none';};type?.addEventListener('change',sync);sync();});})();
</script>
@endpush
