@extends('admin.layout')
@section('title','Donations & Campaigns')
@section('content')
<div class="page-head"><div><h1><i class="fas fa-hand-holding-heart"></i> Donations & Campaigns</h1><p>Manage donation campaigns and review incoming transactions.</p></div><button class="btn btn-primary" data-open-modal="campaign-create"><i class="fas fa-plus"></i> New Campaign</button></div>
<div data-tabs>
<div class="tabs"><button class="tab active" data-tab-target="donations-overview"><i class="fas fa-chart-column"></i> Overview</button><button class="tab" data-tab-target="donations-transactions"><i class="fas fa-receipt"></i> Transactions <span class="tab-count">{{ $donations->total() }}</span></button><button class="tab" data-tab-target="donations-campaigns"><i class="fas fa-bullseye"></i> Campaigns <span class="tab-count">{{ $campaigns->count() }}</span></button></div>
<section id="donations-overview" class="tab-panel active"><div class="grid stats-grid"><div class="card stat-card stat-purple"><i class="fas fa-coins stat-icon"></i><div><strong>{{ number_format($summary['total']) }}</strong><span>Total Donations</span></div></div><div class="card stat-card stat-green"><i class="fas fa-circle-check stat-icon"></i><div><strong>{{ number_format($summary['successful']) }}</strong><span>Successful</span></div></div><div class="card stat-card stat-orange"><i class="fas fa-clock stat-icon"></i><div><strong>{{ number_format($summary['pending']) }}</strong><span>Pending</span></div></div><div class="card stat-card stat-blue"><i class="fas fa-money-bill-trend-up stat-icon"></i><div><strong>UGX {{ number_format($summary['amount_raised'],0) }}</strong><span>Raised</span></div></div></div></section>
<section id="donations-transactions" class="tab-panel"><div class="card"><form method="GET" class="filters"><input type="search" name="search" value="{{ $search }}" placeholder="Search reference, donor, receipt..."><select name="status"><option value="">All statuses</option>@foreach(['pending','successful','paid','completed','failed','cancelled'] as $option)<option value="{{ $option }}" @selected($status===$option)>{{ ucfirst($option) }}</option>@endforeach</select><select name="campaign_id"><option value="">All campaigns</option>@foreach($campaigns as $campaign)<option value="{{ $campaign->id }}" @selected($campaignId===$campaign->id)>{{ $campaign->title }}</option>@endforeach</select><button class="btn btn-primary"><i class="fas fa-filter"></i> Filter</button><a class="btn btn-light" href="{{ route('admin.donations.index') }}#donations-transactions">Reset</a></form></div><div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Reference</th><th>Donor</th><th>Campaign</th><th>Gateway</th><th>Amount</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody>@forelse($donations as $donation)<tr><td><strong>{{ $donation->receipt_number ?: Str::limit($donation->reference,16) }}</strong><small>{{ $donation->external_transaction_id }}</small></td><td>{{ $donation->is_anonymous?'Anonymous':($donation->donor_name ?: optional($donation->user)->name ?: '—') }}<small>{{ $donation->is_anonymous?'':$donation->donor_email }}</small></td><td>{{ optional($donation->campaign)->title ?: 'General Donation' }}</td><td>{{ optional($donation->gateway)->name ?: '—' }}</td><td><strong>{{ $donation->currency }} {{ number_format((float)$donation->amount,0) }}</strong></td><td><span class="badge badge-{{ in_array($donation->status,['successful','paid','completed'])?'success':($donation->status==='pending'?'warning':'danger') }}">{{ ucfirst($donation->status) }}</span></td><td>{{ optional($donation->created_at)->format('d M Y H:i') }}</td><td><button class="icon-btn" data-open-modal="donation-view-{{ $donation->id }}"><i class="fas fa-eye"></i></button></td></tr>@empty<tr><td colspan="8" class="empty">No donations found.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $donations->withQueryString()->links() }}</div></div></section>
<section id="donations-campaigns" class="tab-panel"><div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Campaign</th><th>Status</th><th>Raised</th><th>Target</th><th>Period</th><th>Actions</th></tr></thead><tbody>@forelse($campaigns as $campaign)<tr><td><strong>{{ $campaign->title }}</strong><small>{{ Str::limit(strip_tags($campaign->description),90) }}</small></td><td><span class="badge">{{ ucfirst($campaign->status) }}</span></td><td>{{ $campaign->currency }} {{ number_format((float)($campaign->amount_raised??0),0) }}</td><td>{{ $campaign->target_amount ? $campaign->currency.' '.number_format((float)$campaign->target_amount,0) : 'Open target' }}</td><td>{{ optional($campaign->starts_at)->format('d M Y') ?: 'Any time' }}<small>{{ optional($campaign->ends_at)->format('d M Y') ?: '' }}</small></td><td><div class="actions"><button class="icon-btn" data-open-modal="campaign-view-{{ $campaign->id }}"><i class="fas fa-eye"></i></button><button class="icon-btn" data-open-modal="campaign-edit-{{ $campaign->id }}"><i class="fas fa-pen"></i></button>@if(!$campaign->donations()->exists())<button class="icon-btn" data-open-modal="campaign-delete-{{ $campaign->id }}"><i class="fas fa-trash"></i></button>@endif</div></td></tr>@empty<tr><td colspan="6" class="empty">No donation campaigns have been created yet.</td></tr>@endforelse</tbody></table></div></div></section>
</div>

<div id="campaign-create" class="modal"><div class="modal-card"><div class="modal-head"><h2>New Donation Campaign</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="POST" action="{{ route('admin.donations.campaigns.store') }}">@csrf<div class="form-grid"><label class="span-2">Title<input name="title" required maxlength="190"></label><label class="span-2">Description<textarea name="description" rows="4"></textarea></label><label>Target Amount<input name="target_amount" type="number" min="0" step="0.01"></label><label>Currency<input name="currency" maxlength="3" value="UGX" required></label><label>Starts At<input name="starts_at" type="datetime-local"></label><label>Ends At<input name="ends_at" type="datetime-local"></label><label>Status<select name="status"><option value="draft">Draft</option><option value="published">Published</option><option value="active">Active</option><option value="closed">Closed</option></select></label><label class="checkbox"><input type="checkbox" name="allow_anonymous" value="1" checked> Allow anonymous donations</label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-floppy-disk"></i> Save Campaign</button></div></form></div></div>

@foreach($donations as $donation)
<div id="donation-view-{{ $donation->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>Donation {{ $donation->receipt_number ?: $donation->reference }}</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><div class="detail-grid"><div class="detail-item"><span>Status</span><strong>{{ ucfirst($donation->status) }}</strong></div><div class="detail-item"><span>Amount</span><strong>{{ $donation->currency }} {{ number_format((float)$donation->amount,0) }}</strong></div><div class="detail-item"><span>Donor</span><strong>{{ $donation->is_anonymous?'Anonymous':($donation->donor_name ?: optional($donation->user)->name ?: '—') }}</strong></div><div class="detail-item"><span>Phone</span><strong>{{ $donation->donor_phone ?: '—' }}</strong></div><div class="detail-item"><span>Campaign</span><strong>{{ optional($donation->campaign)->title ?: 'General Donation' }}</strong></div><div class="detail-item"><span>Gateway</span><strong>{{ optional($donation->gateway)->name ?: '—' }}</strong></div><div class="detail-item"><span>Reference</span><strong>{{ $donation->reference }}</strong></div><div class="detail-item"><span>Provider transaction</span><strong>{{ $donation->external_transaction_id ?: '—' }}</strong></div><div class="detail-item"><span>Paid at</span><strong>{{ optional($donation->paid_at)->format('d M Y H:i') ?: '—' }}</strong></div><div class="detail-item"><span>Receipt</span><strong>{{ $donation->receipt_number ?: '—' }}</strong></div></div><div class="modal-actions"><button class="btn btn-light" data-close-modal>Close</button></div></div></div>
@endforeach

@foreach($campaigns as $campaign)
<div id="campaign-view-{{ $campaign->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>{{ $campaign->title }}</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><div class="detail-grid"><div class="detail-item"><span>Status</span><strong>{{ ucfirst($campaign->status) }}</strong></div><div class="detail-item"><span>Currency</span><strong>{{ $campaign->currency }}</strong></div><div class="detail-item"><span>Raised</span><strong>{{ $campaign->currency }} {{ number_format((float)($campaign->amount_raised??0),0) }}</strong></div><div class="detail-item"><span>Target</span><strong>{{ $campaign->target_amount ? number_format((float)$campaign->target_amount,0) : 'Open' }}</strong></div><div class="detail-item"><span>Starts</span><strong>{{ optional($campaign->starts_at)->format('d M Y H:i') ?: '—' }}</strong></div><div class="detail-item"><span>Ends</span><strong>{{ optional($campaign->ends_at)->format('d M Y H:i') ?: '—' }}</strong></div><div class="detail-item span-2"><span>Description</span><strong>{{ $campaign->description ?: '—' }}</strong></div></div><div class="modal-actions"><button class="btn btn-light" data-close-modal>Close</button><button class="btn btn-primary" data-close-modal data-open-modal="campaign-edit-{{ $campaign->id }}"><i class="fas fa-pen"></i> Edit</button></div></div></div>
<div id="campaign-edit-{{ $campaign->id }}" class="modal"><div class="modal-card"><div class="modal-head"><h2>Edit Campaign</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="POST" action="{{ route('admin.donations.campaigns.update',$campaign) }}">@csrf @method('PUT')<div class="form-grid"><label class="span-2">Title<input name="title" value="{{ $campaign->title }}" required maxlength="190"></label><label class="span-2">Description<textarea name="description" rows="4">{{ $campaign->description }}</textarea></label><label>Target Amount<input name="target_amount" type="number" min="0" step="0.01" value="{{ $campaign->target_amount }}"></label><label>Currency<input name="currency" maxlength="3" value="{{ $campaign->currency }}" required></label><label>Starts At<input name="starts_at" type="datetime-local" value="{{ optional($campaign->starts_at)->format('Y-m-d\TH:i') }}"></label><label>Ends At<input name="ends_at" type="datetime-local" value="{{ optional($campaign->ends_at)->format('Y-m-d\TH:i') }}"></label><label>Status<select name="status">@foreach(['draft','published','active','closed'] as $s)<option value="{{ $s }}" @selected($campaign->status===$s)>{{ ucfirst($s) }}</option>@endforeach</select></label><label class="checkbox"><input type="checkbox" name="allow_anonymous" value="1" @checked($campaign->allow_anonymous)> Allow anonymous donations</label></div><div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary"><i class="fas fa-floppy-disk"></i> Update Campaign</button></div></form></div></div>
<div id="campaign-delete-{{ $campaign->id }}" class="modal"><div class="modal-card small"><div class="modal-head"><h2>Delete Campaign?</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><p class="danger-copy">Delete <strong>{{ $campaign->title }}</strong>? This is only available while the campaign has no donations.</p><form method="POST" action="{{ route('admin.donations.campaigns.destroy',$campaign) }}">@csrf @method('DELETE')<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-danger"><i class="fas fa-trash"></i> Delete</button></div></form></div></div>
@endforeach
@endsection
@push('styles')<style>.stat-card{border-left:5px solid var(--primary)}.stat-purple{border-left-color:#7c3aed}.stat-green{border-left-color:#16a34a}.stat-orange{border-left-color:#ea580c}.stat-blue{border-left-color:#2563eb}</style>@endpush
