@extends('admin.layout')
@section('title','Calendar')
@section('content')
<div class="page-head"><div><h1><i class="fas fa-calendar-days"></i> Calendar</h1><p>Combined view of annual work-plan activities, online services and scheduled events.</p></div></div>
<div class="card"><form class="filters" method="GET"><input type="number" name="year" min="2020" max="2100" value="{{ $year }}"><button class="btn btn-primary">View year</button></form></div>
<div class="card" style="margin-top:16px"><div class="calendar-toolbar"><button class="btn btn-light" type="button" id="calPrev"><i class="fas fa-chevron-left"></i></button><h2 id="calTitle" style="margin:0"></h2><button class="btn btn-light" type="button" id="calNext"><i class="fas fa-chevron-right"></i></button></div><div class="calendar-grid calendar-weekdays"><div>Sun</div><div>Mon</div><div>Tue</div><div>Wed</div><div>Thu</div><div>Fri</div><div>Sat</div></div><div class="calendar-grid" id="calendarGrid"></div></div>
<div class="card" style="margin-top:16px"><h3>Year schedule</h3><div class="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Activity</th><th>Details</th></tr></thead><tbody>@forelse($items as $item)<tr><td>{{ \Illuminate\Support\Carbon::parse($item->date)->format('d M Y') }}</td><td><span class="badge">{{ $item->type }}</span></td><td>{{ $item->title }}</td><td>{{ $item->meta }}</td></tr>@empty<tr><td colspan="4" class="empty">No calendar items for {{ $year }}.</td></tr>@endforelse</tbody></table></div></div>
<style>.calendar-toolbar{display:flex;align-items:center;justify-content:center;gap:14px;margin-bottom:14px}.calendar-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:6px}.calendar-weekdays>div{text-align:center;font-size:12px;font-weight:800;color:var(--muted);padding:8px}.calendar-day{min-height:105px;border:1px solid var(--border);border-radius:11px;padding:8px;background:#fff}.calendar-day.muted{opacity:.42}.calendar-date{font-weight:800;font-size:12px;margin-bottom:6px}.calendar-event{font-size:11px;line-height:1.3;padding:5px 6px;margin:4px 0;border-radius:7px;background:var(--primary-soft);color:var(--primary);font-weight:700;overflow:hidden;text-overflow:ellipsis}@media(max-width:800px){.calendar-grid{gap:3px}.calendar-day{min-height:78px;padding:5px}.calendar-event{font-size:9px;padding:3px}.calendar-weekdays>div{font-size:10px;padding:5px}}</style>
<script>
document.addEventListener('DOMContentLoaded',()=>{const items=@json($items);let current=new Date({{ $year }},new Date().getFullYear()==={{ $year }}?new Date().getMonth():0,1);const grid=document.getElementById('calendarGrid'),title=document.getElementById('calTitle');const render=()=>{grid.innerHTML='';title.textContent=current.toLocaleString(undefined,{month:'long',year:'numeric'});const y=current.getFullYear(),m=current.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay());for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const cell=document.createElement('div');cell.className='calendar-day'+(d.getMonth()!==m?' muted':'');cell.innerHTML=`<div class="calendar-date">${d.getDate()}</div>`;items.filter(x=>x.date===iso).slice(0,3).forEach(x=>{const e=document.createElement('div');e.className='calendar-event';e.title=x.type+': '+x.title;e.textContent=x.title;cell.appendChild(e)});grid.appendChild(cell)}};document.getElementById('calPrev').onclick=()=>{current.setMonth(current.getMonth()-1);render()};document.getElementById('calNext').onclick=()=>{current.setMonth(current.getMonth()+1);render()};render();});
</script>
@endsection
