@extends('admin.layout')
@section('title','Annual Themes')
@section('content')
<div class="page-head"><div><h1><i class="fas fa-book-open"></i> Annual Themes</h1><p>Manage yearly youth ministry themes, scriptures and publication status.</p></div><button class="btn btn-primary" data-open-modal="theme-add"><i class="fas fa-plus"></i> Add theme</button></div>
<div class="card"><form class="filters" method="GET"><input name="q" placeholder="Search themes or scripture" value="{{ request('q') }}"><button class="btn btn-primary">Search</button><a class="btn btn-light" href="{{ route('admin.annual-themes.index') }}">Reset</a></form></div>
<div class="grid" style="margin-top:16px">@forelse($themes as $t)<div class="card">@if($t->image_path)<img src="{{ asset('storage/'.$t->image_path) }}" alt="" style="width:100%;height:150px;object-fit:cover;border-radius:12px;margin-bottom:12px">@endif<div class="campaign-top"><h3>{{ $t->year }} — {{ $t->theme }}</h3><span class="badge {{ $t->is_published ? 'badge-success' : '' }}">{{ $t->is_published ? 'Published' : 'Draft' }}</span></div><p class="muted"><strong>{{ $t->scripture_reference ?: 'No scripture reference' }}</strong></p><p>{{ \Illuminate\Support\Str::limit($t->description,150) }}</p><div class="actions"><button class="btn btn-light" data-open-modal="theme-edit-{{ $t->id }}">Edit</button><button class="btn btn-danger" data-open-modal="theme-delete-{{ $t->id }}">Delete</button></div></div>@empty<div class="card empty">No annual themes yet.</div>@endforelse</div><div class="pagination">{{ $themes->links() }}</div>
<div class="modal" id="theme-add"><div class="modal-card"><div class="modal-head"><h2>Add Annual Theme</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="POST" enctype="multipart/form-data" action="{{ route('admin.annual-themes.store') }}">@csrf @include('admin.planning._theme-fields',['theme'=>null])<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary">Save</button></div></form></div></div>
@foreach($themes as $t)<div class="modal" id="theme-edit-{{ $t->id }}"><div class="modal-card"><div class="modal-head"><h2>Edit Annual Theme</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="POST" enctype="multipart/form-data" action="{{ route('admin.annual-themes.update',$t->id) }}">@csrf @method('PUT') @include('admin.planning._theme-fields',['theme'=>$t])<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary">Update</button></div></form></div></div><div class="modal" id="theme-delete-{{ $t->id }}"><div class="modal-card small"><div class="modal-head"><h2>Delete annual theme?</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><p>{{ $t->year }} — {{ $t->theme }}</p><form method="POST" action="{{ route('admin.annual-themes.destroy',$t->id) }}">@csrf @method('DELETE')<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-danger">Delete</button></div></form></div></div>@endforeach
@endsection
