@extends('admin.layout')
@section('title','Annual Work Plans')
@section('content')
<div class="page-head"><div><h1><i class="fas fa-list-check"></i> Annual Work Plans</h1><p>Plan objectives, activities, budgets, responsibilities and progress by year.</p></div><button class="btn btn-primary" data-open-modal="workplan-add"><i class="fas fa-plus"></i> Add work plan</button></div>
<div class="grid stats-grid"><div class="card stat-card"><span class="stat-icon"><i class="fas fa-list"></i></span><div><strong>{{ $stats['total'] }}</strong><span>Total plans</span></div></div><div class="card stat-card"><span class="stat-icon"><i class="fas fa-spinner"></i></span><div><strong>{{ $stats['active'] }}</strong><span>Active</span></div></div><div class="card stat-card"><span class="stat-icon"><i class="fas fa-circle-check"></i></span><div><strong>{{ $stats['completed'] }}</strong><span>Completed</span></div></div><div class="card stat-card"><span class="stat-icon"><i class="fas fa-wallet"></i></span><div><strong>{{ number_format($stats['budget']) }}</strong><span>Total budget</span></div></div></div>
<div class="card"><form class="filters" method="GET"><input name="q" placeholder="Search plans" value="{{ request('q') }}"><input name="year" type="number" placeholder="Year" value="{{ request('year') }}"><select name="status"><option value="">All statuses</option>@foreach(['planned','in_progress','completed','on_hold','cancelled'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ ucwords(str_replace('_',' ',$s)) }}</option>@endforeach</select><button class="btn btn-primary">Filter</button><a class="btn btn-light" href="{{ route('admin.work-plans.index') }}">Reset</a></form></div>
<div class="card table-card"><div class="table-wrap"><table><thead><tr><th>Year</th><th>Plan</th><th>Dates</th><th>Budget</th><th>Progress</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($plans as $p)<tr><td>{{ $p->year }}</td><td><strong>{{ $p->title }}</strong><small>{{ $p->department ?: 'No department' }} @if($p->responsible_person) · {{ $p->responsible_person }} @endif</small></td><td>{{ $p->start_date ?: '—' }}<small>{{ $p->end_date ?: '' }}</small></td><td>{{ number_format((float)$p->budget) }}</td><td>{{ $p->progress_percent }}%</td><td><span class="badge">{{ ucwords(str_replace('_',' ',$p->status)) }}</span></td><td class="actions"><button class="btn btn-light" data-open-modal="wp-view-{{ $p->id }}">View</button><button class="btn btn-light" data-open-modal="wp-edit-{{ $p->id }}">Edit</button><button class="btn btn-danger" data-open-modal="wp-delete-{{ $p->id }}">Delete</button></td></tr>@empty<tr><td colspan="7" class="empty">No work plans found.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $plans->links() }}</div></div>
<div class="modal" id="workplan-add"><div class="modal-card large"><div class="modal-head"><h2>Add Annual Work Plan</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="POST" action="{{ route('admin.work-plans.store') }}">@csrf @include('admin.planning._work-plan-fields',['plan'=>null])<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary">Save</button></div></form></div></div>
@foreach($plans as $p)
<div class="modal" id="wp-view-{{ $p->id }}"><div class="modal-card"><div class="modal-head"><h2>{{ $p->title }}</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><div class="detail-grid"><div class="detail-item"><span>Objective</span><strong>{{ $p->objective ?: '—' }}</strong></div><div class="detail-item"><span>Activity</span><strong>{{ $p->activity ?: '—' }}</strong></div><div class="detail-item"><span>Responsible</span><strong>{{ $p->responsible_person ?: '—' }}</strong></div><div class="detail-item"><span>Notes</span><strong>{{ $p->notes ?: '—' }}</strong></div></div></div></div>
<div class="modal" id="wp-edit-{{ $p->id }}"><div class="modal-card large"><div class="modal-head"><h2>Edit Work Plan</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><form method="POST" action="{{ route('admin.work-plans.update',$p->id) }}">@csrf @method('PUT') @include('admin.planning._work-plan-fields',['plan'=>$p])<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-primary">Update</button></div></form></div></div>
<div class="modal" id="wp-delete-{{ $p->id }}"><div class="modal-card small"><div class="modal-head"><h2>Delete work plan?</h2><button class="icon-btn" data-close-modal><i class="fas fa-xmark"></i></button></div><p>This permanently removes <strong>{{ $p->title }}</strong>.</p><form method="POST" action="{{ route('admin.work-plans.destroy',$p->id) }}">@csrf @method('DELETE')<div class="modal-actions"><button type="button" class="btn btn-light" data-close-modal>Cancel</button><button class="btn btn-danger">Delete</button></div></form></div></div>
@endforeach
@endsection
