<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Models\Event; use App\Services\Access\HierarchyScopeService; use Illuminate\Http\Request;
class EventController extends Controller { public function __construct(private HierarchyScopeService $scope){}
 public function index(){ return view('admin.events.index',['events'=>Event::with('organisationUnit')->orderByDesc('starts_at')->paginate(25)]); }
 public function store(Request $r){ $data=$this->validated($r); if(!empty($data['organisation_unit_id'])&&!$this->scope->canManage($r->user(),(int)$data['organisation_unit_id']))abort(403); $data['created_by']=$r->user()->id; Event::create($data); return back()->with('success','Event created successfully.'); }
 public function update(Request $r, Event $event){ if($event->organisation_unit_id&&!$this->scope->canManage($r->user(),$event->organisation_unit_id))abort(403); $event->update($this->validated($r)); return back()->with('success','Event updated successfully.'); }
 public function destroy(Request $r, Event $event){ if($event->organisation_unit_id&&!$this->scope->canManage($r->user(),$event->organisation_unit_id))abort(403); $event->delete(); return back()->with('success','Event deleted.'); }
 private function validated(Request $r): array { return $r->validate(['organisation_unit_id'=>'nullable|exists:organisation_units,id','title'=>'required|max:200','category'=>'nullable|max:100','description'=>'nullable','starts_at'=>'required|date','ends_at'=>'nullable|date|after_or_equal:starts_at','venue'=>'nullable|max:200','theme'=>'nullable|max:200','speaker'=>'nullable|max:160','organizer'=>'nullable|max:160','target_age_categories'=>'nullable|array','target_age_categories.*'=>'in:teen,youth,young_adult','registration_required'=>'boolean','fee'=>'nullable|numeric|min:0','currency'=>'required|size:3','capacity'=>'nullable|integer|min:1','registration_deadline'=>'nullable|date','status'=>'required|in:draft,published,cancelled,completed']); }
}
